// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chat.proto

package protos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED    SessionType = 0
	SessionType_SESSION_TYPE_WORKFLOW       SessionType = 1
	SessionType_SESSION_TYPE_CHAT           SessionType = 2
	SessionType_SESSION_TYPE_TOOL_DISCOVERY SessionType = 3
	SessionType_SESSION_TYPE_ASSISTANCE     SessionType = 4
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_WORKFLOW",
		2: "SESSION_TYPE_CHAT",
		3: "SESSION_TYPE_TOOL_DISCOVERY",
		4: "SESSION_TYPE_ASSISTANCE",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED":    0,
		"SESSION_TYPE_WORKFLOW":       1,
		"SESSION_TYPE_CHAT":           2,
		"SESSION_TYPE_TOOL_DISCOVERY": 3,
		"SESSION_TYPE_ASSISTANCE":     4,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[0].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[0]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED MessageType = 0
	MessageType_MESSAGE_TYPE_USER        MessageType = 1
	MessageType_MESSAGE_TYPE_ASSISTANT   MessageType = 2
	MessageType_MESSAGE_TYPE_SYSTEM      MessageType = 3
	MessageType_MESSAGE_TYPE_TOOL_CALL   MessageType = 4
	MessageType_MESSAGE_TYPE_TOOL_RESULT MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_USER",
		2: "MESSAGE_TYPE_ASSISTANT",
		3: "MESSAGE_TYPE_SYSTEM",
		4: "MESSAGE_TYPE_TOOL_CALL",
		5: "MESSAGE_TYPE_TOOL_RESULT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED": 0,
		"MESSAGE_TYPE_USER":        1,
		"MESSAGE_TYPE_ASSISTANT":   2,
		"MESSAGE_TYPE_SYSTEM":      3,
		"MESSAGE_TYPE_TOOL_CALL":   4,
		"MESSAGE_TYPE_TOOL_RESULT": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_ENDED       SessionStatus = 2
	SessionStatus_SESSION_STATUS_ERROR       SessionStatus = 3
	SessionStatus_SESSION_STATUS_TIMEOUT     SessionStatus = 4
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_ENDED",
		3: "SESSION_STATUS_ERROR",
		4: "SESSION_STATUS_TIMEOUT",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_ENDED":       2,
		"SESSION_STATUS_ERROR":       3,
		"SESSION_STATUS_TIMEOUT":     4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[2].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[2]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_UNSPECIFIED ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_SUCCESS     ResponseStatus = 1
	ResponseStatus_RESPONSE_STATUS_PROCESSING  ResponseStatus = 2
	ResponseStatus_RESPONSE_STATUS_ERROR       ResponseStatus = 3
	ResponseStatus_RESPONSE_STATUS_PARTIAL     ResponseStatus = 4
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "RESPONSE_STATUS_UNSPECIFIED",
		1: "RESPONSE_STATUS_SUCCESS",
		2: "RESPONSE_STATUS_PROCESSING",
		3: "RESPONSE_STATUS_ERROR",
		4: "RESPONSE_STATUS_PARTIAL",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_UNSPECIFIED": 0,
		"RESPONSE_STATUS_SUCCESS":     1,
		"RESPONSE_STATUS_PROCESSING":  2,
		"RESPONSE_STATUS_ERROR":       3,
		"RESPONSE_STATUS_PARTIAL":     4,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[3].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[3]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

type ToolCallStatus int32

const (
	ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED ToolCallStatus = 0
	ToolCallStatus_TOOL_CALL_STATUS_PENDING     ToolCallStatus = 1
	ToolCallStatus_TOOL_CALL_STATUS_SUCCESS     ToolCallStatus = 2
	ToolCallStatus_TOOL_CALL_STATUS_ERROR       ToolCallStatus = 3
	ToolCallStatus_TOOL_CALL_STATUS_TIMEOUT     ToolCallStatus = 4
)

// Enum value maps for ToolCallStatus.
var (
	ToolCallStatus_name = map[int32]string{
		0: "TOOL_CALL_STATUS_UNSPECIFIED",
		1: "TOOL_CALL_STATUS_PENDING",
		2: "TOOL_CALL_STATUS_SUCCESS",
		3: "TOOL_CALL_STATUS_ERROR",
		4: "TOOL_CALL_STATUS_TIMEOUT",
	}
	ToolCallStatus_value = map[string]int32{
		"TOOL_CALL_STATUS_UNSPECIFIED": 0,
		"TOOL_CALL_STATUS_PENDING":     1,
		"TOOL_CALL_STATUS_SUCCESS":     2,
		"TOOL_CALL_STATUS_ERROR":       3,
		"TOOL_CALL_STATUS_TIMEOUT":     4,
	}
)

func (x ToolCallStatus) Enum() *ToolCallStatus {
	p := new(ToolCallStatus)
	*p = x
	return p
}

func (x ToolCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_proto_enumTypes[4].Descriptor()
}

func (ToolCallStatus) Type() protoreflect.EnumType {
	return &file_chat_proto_enumTypes[4]
}

func (x ToolCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCallStatus.Descriptor instead.
func (ToolCallStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

type StartChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionType   SessionType            `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=ai-workflow-automation.chat.SessionType" json:"session_type,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChatSessionRequest) Reset() {
	*x = StartChatSessionRequest{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatSessionRequest) ProtoMessage() {}

func (x *StartChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatSessionRequest.ProtoReflect.Descriptor instead.
func (*StartChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *StartChatSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StartChatSessionRequest) GetSessionType() SessionType {
	if x != nil {
		return x.SessionType
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *StartChatSessionRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StartChatSessionRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageType    MessageType            `protobuf:"varint,3,opt,name=message_type,json=messageType,proto3,enum=ai-workflow-automation.chat.MessageType" json:"message_type,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	StreamResponse bool                   `protobuf:"varint,5,opt,name=stream_response,json=streamResponse,proto3" json:"stream_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *SendMessageRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SendMessageRequest) GetStreamResponse() bool {
	if x != nil {
		return x.StreamResponse
	}
	return false
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetChatHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetChatHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetChatHistoryRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetChatHistoryRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type EndChatSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndChatSessionRequest) Reset() {
	*x = EndChatSessionRequest{}
	mi := &file_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndChatSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndChatSessionRequest) ProtoMessage() {}

func (x *EndChatSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndChatSessionRequest.ProtoReflect.Descriptor instead.
func (*EndChatSessionRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *EndChatSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndChatSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetSessionContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionContextRequest) Reset() {
	*x = GetSessionContextRequest{}
	mi := &file_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionContextRequest) ProtoMessage() {}

func (x *GetSessionContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionContextRequest.ProtoReflect.Descriptor instead.
func (*GetSessionContextRequest) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StartChatSessionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status         SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ai-workflow-automation.chat.SessionStatus" json:"status,omitempty"`
	Context        *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	AvailableTools []string               `protobuf:"bytes,4,rep,name=available_tools,json=availableTools,proto3" json:"available_tools,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartChatSessionResponse) Reset() {
	*x = StartChatSessionResponse{}
	mi := &file_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatSessionResponse) ProtoMessage() {}

func (x *StartChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatSessionResponse.ProtoReflect.Descriptor instead.
func (*StartChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{5}
}

func (x *StartChatSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartChatSessionResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *StartChatSessionResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *StartChatSessionResponse) GetAvailableTools() []string {
	if x != nil {
		return x.AvailableTools
	}
	return nil
}

func (x *StartChatSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChatMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=ai-workflow-automation.chat.MessageType" json:"message_type,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=ai-workflow-automation.chat.ResponseStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsFinal       bool                   `protobuf:"varint,8,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,9,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessageResponse) Reset() {
	*x = ChatMessageResponse{}
	mi := &file_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageResponse) ProtoMessage() {}

func (x *ChatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageResponse.ProtoReflect.Descriptor instead.
func (*ChatMessageResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessageResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessageResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatMessageResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_UNSPECIFIED
}

func (x *ChatMessageResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatMessageResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatMessageResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ChatMessageResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetChatHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetChatHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetChatHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type EndChatSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ai-workflow-automation.chat.SessionStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndChatSessionResponse) Reset() {
	*x = EndChatSessionResponse{}
	mi := &file_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndChatSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndChatSessionResponse) ProtoMessage() {}

func (x *EndChatSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndChatSessionResponse.ProtoReflect.Descriptor instead.
func (*EndChatSessionResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{8}
}

func (x *EndChatSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EndChatSessionResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *EndChatSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EndChatSessionResponse) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type GetSessionContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=ai-workflow-automation.chat.SessionStatus" json:"status,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	ActiveTools   []string               `protobuf:"bytes,4,rep,name=active_tools,json=activeTools,proto3" json:"active_tools,omitempty"`
	Metrics       *SessionMetrics        `protobuf:"bytes,5,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionContextResponse) Reset() {
	*x = GetSessionContextResponse{}
	mi := &file_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionContextResponse) ProtoMessage() {}

func (x *GetSessionContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionContextResponse.ProtoReflect.Descriptor instead.
func (*GetSessionContextResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionContextResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionContextResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *GetSessionContextResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetSessionContextResponse) GetActiveTools() []string {
	if x != nil {
		return x.ActiveTools
	}
	return nil
}

func (x *GetSessionContextResponse) GetMetrics() *SessionMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MessageType   MessageType            `protobuf:"varint,4,opt,name=message_type,json=messageType,proto3,enum=ai-workflow-automation.chat.MessageType" json:"message_type,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,7,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ChatMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ChatMessage) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ChatMessage) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Result        string                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Status        ToolCallStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=ai-workflow-automation.chat.ToolCallStatus" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ToolCall) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCall) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCall) GetStatus() ToolCallStatus {
	if x != nil {
		return x.Status
	}
	return ToolCallStatus_TOOL_CALL_STATUS_UNSPECIFIED
}

func (x *ToolCall) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SessionMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageCount    int32                  `protobuf:"varint,1,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	ToolCallsCount  int32                  `protobuf:"varint,2,opt,name=tool_calls_count,json=toolCallsCount,proto3" json:"tool_calls_count,omitempty"`
	SessionDuration *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=session_duration,json=sessionDuration,proto3" json:"session_duration,omitempty"`
	TokensUsed      int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionMetrics) Reset() {
	*x = SessionMetrics{}
	mi := &file_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetrics) ProtoMessage() {}

func (x *SessionMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMetrics.ProtoReflect.Descriptor instead.
func (*SessionMetrics) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{12}
}

func (x *SessionMetrics) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionMetrics) GetToolCallsCount() int32 {
	if x != nil {
		return x.ToolCallsCount
	}
	return 0
}

func (x *SessionMetrics) GetSessionDuration() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionDuration
	}
	return nil
}

func (x *SessionMetrics) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\rverbilio.chat\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc8\x01\n" +
	"\x17StartChatSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12=\n" +
	"\fsession_type\x18\x02 \x01(\x0e2\x1a.ai-workflow-automation.chat.SessionTypeR\vsessionType\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xea\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\fmessage_type\x18\x03 \x01(\x0e2\x1a.ai-workflow-automation.chat.MessageTypeR\vmessageType\x123\n" +
	"\bmetadata\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12'\n" +
	"\x0fstream_response\x18\x05 \x01(\bR\x0estreamResponse\"\xd6\x01\n" +
	"\x15GetChatHistoryRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"N\n" +
	"\x15EndChatSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"9\n" +
	"\x18GetSessionContextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xe5\x01\n" +
	"\x18StartChatSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.ai-workflow-automation.chat.SessionStatusR\x06status\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12'\n" +
	"\x0favailable_tools\x18\x04 \x03(\tR\x0eavailableTools\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xa5\x03\n" +
	"\x13ChatMessageResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12=\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x1a.ai-workflow-automation.chat.MessageTypeR\vmessageType\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.ai-workflow-automation.chat.ResponseStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x19\n" +
	"\bis_final\x18\b \x01(\bR\aisFinal\x126\n" +
	"\n" +
	"tool_calls\x18\t \x03(\v2\x17.ai-workflow-automation.chat.ToolCallR\ttoolCalls\"\xad\x01\n" +
	"\x16GetChatHistoryResponse\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.ai-workflow-automation.chat.ChatMessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\"\xbe\x01\n" +
	"\x16EndChatSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.ai-workflow-automation.chat.SessionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x125\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xff\x01\n" +
	"\x19GetSessionContextResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.ai-workflow-automation.chat.SessionStatusR\x06status\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12!\n" +
	"\factive_tools\x18\x04 \x03(\tR\vactiveTools\x127\n" +
	"\ametrics\x18\x05 \x01(\v2\x1d.ai-workflow-automation.chat.SessionMetricsR\ametrics\"\xcb\x02\n" +
	"\vChatMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12=\n" +
	"\fmessage_type\x18\x04 \x01(\x0e2\x1a.ai-workflow-automation.chat.MessageTypeR\vmessageType\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bmetadata\x18\x06 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x126\n" +
	"\n" +
	"tool_calls\x18\a \x03(\v2\x17.ai-workflow-automation.chat.ToolCallR\ttoolCalls\"\x80\x02\n" +
	"\bToolCall\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\x12\x16\n" +
	"\x06result\x18\x04 \x01(\tR\x06result\x125\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1d.ai-workflow-automation.chat.ToolCallStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc7\x01\n" +
	"\x0eSessionMetrics\x12#\n" +
	"\rmessage_count\x18\x01 \x01(\x05R\fmessageCount\x12(\n" +
	"\x10tool_calls_count\x18\x02 \x01(\x05R\x0etoolCallsCount\x12E\n" +
	"\x10session_duration\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fsessionDuration\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed*\x9b\x01\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_TYPE_WORKFLOW\x10\x01\x12\x15\n" +
	"\x11SESSION_TYPE_CHAT\x10\x02\x12\x1f\n" +
	"\x1bSESSION_TYPE_TOOL_DISCOVERY\x10\x03\x12\x1b\n" +
	"\x17SESSION_TYPE_ASSISTANCE\x10\x04*\xb1\x01\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_TYPE_ASSISTANT\x10\x02\x12\x17\n" +
	"\x13MESSAGE_TYPE_SYSTEM\x10\x03\x12\x1a\n" +
	"\x16MESSAGE_TYPE_TOOL_CALL\x10\x04\x12\x1c\n" +
	"\x18MESSAGE_TYPE_TOOL_RESULT\x10\x05*\x9a\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14SESSION_STATUS_ENDED\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x03\x12\x1a\n" +
	"\x16SESSION_STATUS_TIMEOUT\x10\x04*\xa6\x01\n" +
	"\x0eResponseStatus\x12\x1f\n" +
	"\x1bRESPONSE_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESPONSE_STATUS_SUCCESS\x10\x01\x12\x1e\n" +
	"\x1aRESPONSE_STATUS_PROCESSING\x10\x02\x12\x19\n" +
	"\x15RESPONSE_STATUS_ERROR\x10\x03\x12\x1b\n" +
	"\x17RESPONSE_STATUS_PARTIAL\x10\x04*\xa8\x01\n" +
	"\x0eToolCallStatus\x12 \n" +
	"\x1cTOOL_CALL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_SUCCESS\x10\x02\x12\x1a\n" +
	"\x16TOOL_CALL_STATUS_ERROR\x10\x03\x12\x1c\n" +
	"\x18TOOL_CALL_STATUS_TIMEOUT\x10\x042\xf0\x03\n" +
	"\vChatService\x12c\n" +
	"\x10StartChatSession\x12&.ai-workflow-automation.chat.StartChatSessionRequest\x1a'.ai-workflow-automation.chat.StartChatSessionResponse\x12V\n" +
	"\vSendMessage\x12!.ai-workflow-automation.chat.SendMessageRequest\x1a\".ai-workflow-automation.chat.ChatMessageResponse0\x01\x12]\n" +
	"\x0eGetChatHistory\x12$.ai-workflow-automation.chat.GetChatHistoryRequest\x1a%.ai-workflow-automation.chat.GetChatHistoryResponse\x12]\n" +
	"\x0eEndChatSession\x12$.ai-workflow-automation.chat.EndChatSessionRequest\x1a%.ai-workflow-automation.chat.EndChatSessionResponse\x12f\n" +
	"\x11GetSessionContext\x12'.ai-workflow-automation.chat.GetSessionContextRequest\x1a(.ai-workflow-automation.chat.GetSessionContextResponseB8Z6github.com/ai-workflow-automation/api-gateway/pkg/grpc_client/protosb\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_proto_goTypes = []any{
	(SessionType)(0),                  // 0: ai-workflow-automation.chat.SessionType
	(MessageType)(0),                  // 1: ai-workflow-automation.chat.MessageType
	(SessionStatus)(0),                // 2: ai-workflow-automation.chat.SessionStatus
	(ResponseStatus)(0),               // 3: ai-workflow-automation.chat.ResponseStatus
	(ToolCallStatus)(0),               // 4: ai-workflow-automation.chat.ToolCallStatus
	(*StartChatSessionRequest)(nil),   // 5: ai-workflow-automation.chat.StartChatSessionRequest
	(*SendMessageRequest)(nil),        // 6: ai-workflow-automation.chat.SendMessageRequest
	(*GetChatHistoryRequest)(nil),     // 7: ai-workflow-automation.chat.GetChatHistoryRequest
	(*EndChatSessionRequest)(nil),     // 8: ai-workflow-automation.chat.EndChatSessionRequest
	(*GetSessionContextRequest)(nil),  // 9: ai-workflow-automation.chat.GetSessionContextRequest
	(*StartChatSessionResponse)(nil),  // 10: ai-workflow-automation.chat.StartChatSessionResponse
	(*ChatMessageResponse)(nil),       // 11: ai-workflow-automation.chat.ChatMessageResponse
	(*GetChatHistoryResponse)(nil),    // 12: ai-workflow-automation.chat.GetChatHistoryResponse
	(*EndChatSessionResponse)(nil),    // 13: ai-workflow-automation.chat.EndChatSessionResponse
	(*GetSessionContextResponse)(nil), // 14: ai-workflow-automation.chat.GetSessionContextResponse
	(*ChatMessage)(nil),               // 15: ai-workflow-automation.chat.ChatMessage
	(*ToolCall)(nil),                  // 16: ai-workflow-automation.chat.ToolCall
	(*SessionMetrics)(nil),            // 17: ai-workflow-automation.chat.SessionMetrics
	(*structpb.Struct)(nil),           // 18: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),     // 19: google.protobuf.Timestamp
}
var file_chat_proto_depIdxs = []int32{
	0,  // 0: ai-workflow-automation.chat.StartChatSessionRequest.session_type:type_name -> ai-workflow-automation.chat.SessionType
	18, // 1: ai-workflow-automation.chat.StartChatSessionRequest.context:type_name -> google.protobuf.Struct
	1,  // 2: ai-workflow-automation.chat.SendMessageRequest.message_type:type_name -> ai-workflow-automation.chat.MessageType
	18, // 3: ai-workflow-automation.chat.SendMessageRequest.metadata:type_name -> google.protobuf.Struct
	19, // 4: ai-workflow-automation.chat.GetChatHistoryRequest.start_time:type_name -> google.protobuf.Timestamp
	19, // 5: ai-workflow-automation.chat.GetChatHistoryRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 6: ai-workflow-automation.chat.StartChatSessionResponse.status:type_name -> ai-workflow-automation.chat.SessionStatus
	18, // 7: ai-workflow-automation.chat.StartChatSessionResponse.context:type_name -> google.protobuf.Struct
	1,  // 8: ai-workflow-automation.chat.ChatMessageResponse.message_type:type_name -> ai-workflow-automation.chat.MessageType
	3,  // 9: ai-workflow-automation.chat.ChatMessageResponse.status:type_name -> ai-workflow-automation.chat.ResponseStatus
	19, // 10: ai-workflow-automation.chat.ChatMessageResponse.timestamp:type_name -> google.protobuf.Timestamp
	18, // 11: ai-workflow-automation.chat.ChatMessageResponse.metadata:type_name -> google.protobuf.Struct
	16, // 12: ai-workflow-automation.chat.ChatMessageResponse.tool_calls:type_name -> ai-workflow-automation.chat.ToolCall
	15, // 13: ai-workflow-automation.chat.GetChatHistoryResponse.messages:type_name -> ai-workflow-automation.chat.ChatMessage
	2,  // 14: ai-workflow-automation.chat.EndChatSessionResponse.status:type_name -> ai-workflow-automation.chat.SessionStatus
	19, // 15: ai-workflow-automation.chat.EndChatSessionResponse.ended_at:type_name -> google.protobuf.Timestamp
	2,  // 16: ai-workflow-automation.chat.GetSessionContextResponse.status:type_name -> ai-workflow-automation.chat.SessionStatus
	18, // 17: ai-workflow-automation.chat.GetSessionContextResponse.context:type_name -> google.protobuf.Struct
	17, // 18: ai-workflow-automation.chat.GetSessionContextResponse.metrics:type_name -> ai-workflow-automation.chat.SessionMetrics
	1,  // 19: ai-workflow-automation.chat.ChatMessage.message_type:type_name -> ai-workflow-automation.chat.MessageType
	19, // 20: ai-workflow-automation.chat.ChatMessage.timestamp:type_name -> google.protobuf.Timestamp
	18, // 21: ai-workflow-automation.chat.ChatMessage.metadata:type_name -> google.protobuf.Struct
	16, // 22: ai-workflow-automation.chat.ChatMessage.tool_calls:type_name -> ai-workflow-automation.chat.ToolCall
	18, // 23: ai-workflow-automation.chat.ToolCall.arguments:type_name -> google.protobuf.Struct
	4,  // 24: ai-workflow-automation.chat.ToolCall.status:type_name -> ai-workflow-automation.chat.ToolCallStatus
	19, // 25: ai-workflow-automation.chat.ToolCall.timestamp:type_name -> google.protobuf.Timestamp
	19, // 26: ai-workflow-automation.chat.SessionMetrics.session_duration:type_name -> google.protobuf.Timestamp
	5,  // 27: ai-workflow-automation.chat.ChatService.StartChatSession:input_type -> ai-workflow-automation.chat.StartChatSessionRequest
	6,  // 28: ai-workflow-automation.chat.ChatService.SendMessage:input_type -> ai-workflow-automation.chat.SendMessageRequest
	7,  // 29: ai-workflow-automation.chat.ChatService.GetChatHistory:input_type -> ai-workflow-automation.chat.GetChatHistoryRequest
	8,  // 30: ai-workflow-automation.chat.ChatService.EndChatSession:input_type -> ai-workflow-automation.chat.EndChatSessionRequest
	9,  // 31: ai-workflow-automation.chat.ChatService.GetSessionContext:input_type -> ai-workflow-automation.chat.GetSessionContextRequest
	10, // 32: ai-workflow-automation.chat.ChatService.StartChatSession:output_type -> ai-workflow-automation.chat.StartChatSessionResponse
	11, // 33: ai-workflow-automation.chat.ChatService.SendMessage:output_type -> ai-workflow-automation.chat.ChatMessageResponse
	12, // 34: ai-workflow-automation.chat.ChatService.GetChatHistory:output_type -> ai-workflow-automation.chat.GetChatHistoryResponse
	13, // 35: ai-workflow-automation.chat.ChatService.EndChatSession:output_type -> ai-workflow-automation.chat.EndChatSessionResponse
	14, // 36: ai-workflow-automation.chat.ChatService.GetSessionContext:output_type -> ai-workflow-automation.chat.GetSessionContextResponse
	32, // [32:37] is the sub-list for method output_type
	27, // [27:32] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		EnumInfos:         file_chat_proto_enumTypes,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
