// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: execution.proto

package protos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request Messages
type ExecuteWorkflowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId     string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TestMode       bool                   `protobuf:"varint,3,opt,name=test_mode,json=testMode,proto3" json:"test_mode,omitempty"`
	CorrelationId  string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Parameters     *structpb.Struct       `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	StreamProgress bool                   `protobuf:"varint,6,opt,name=stream_progress,json=streamProgress,proto3" json:"stream_progress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteWorkflowRequest) Reset() {
	*x = ExecuteWorkflowRequest{}
	mi := &file_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowRequest) ProtoMessage() {}

func (x *ExecuteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

func (x *ExecuteWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecuteWorkflowRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteWorkflowRequest) GetStreamProgress() bool {
	if x != nil {
		return x.StreamProgress
	}
	return false
}

type GetExecutionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusRequest) Reset() {
	*x = GetExecutionStatusRequest{}
	mi := &file_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusRequest) ProtoMessage() {}

func (x *GetExecutionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{1}
}

func (x *GetExecutionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExecutionStatusRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type CancelExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionRequest) Reset() {
	*x = CancelExecutionRequest{}
	mi := &file_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionRequest) ProtoMessage() {}

func (x *CancelExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionRequest.ProtoReflect.Descriptor instead.
func (*CancelExecutionRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{2}
}

func (x *CancelExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CancelExecutionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelExecutionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CancelExecutionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"` // Optional filter
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // Optional filter
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ListExecutionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListExecutionsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ListExecutionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExecutionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListExecutionsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetExecutionLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionLogsRequest) Reset() {
	*x = GetExecutionLogsRequest{}
	mi := &file_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionLogsRequest) ProtoMessage() {}

func (x *GetExecutionLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionLogsRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionLogsRequest) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{4}
}

func (x *GetExecutionLogsRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *GetExecutionLogsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetExecutionLogsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GetExecutionLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetExecutionLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response Messages
type ExecuteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Metadata      *ExecutionMetadata     `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkflowResponse) Reset() {
	*x = ExecuteWorkflowResponse{}
	mi := &file_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkflowResponse) ProtoMessage() {}

func (x *ExecuteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteWorkflowResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ExecuteWorkflowResponse) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ExecutionUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId        string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId             string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StepName           string                 `protobuf:"bytes,3,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "step_start", "step_complete", "step_error", "execution_complete"
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Message            string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	ProgressPercentage float32                `protobuf:"fixed32,7,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	Timestamp          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data               *structpb.Struct       `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Error              string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ExecutionUpdate) Reset() {
	*x = ExecutionUpdate{}
	mi := &file_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionUpdate) ProtoMessage() {}

func (x *ExecutionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionUpdate.ProtoReflect.Descriptor instead.
func (*ExecutionUpdate) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionUpdate) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionUpdate) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionUpdate) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecutionUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutionUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionUpdate) GetProgressPercentage() float32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *ExecutionUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutionUpdate) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutionUpdate) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetExecutionStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *ExecutionResult       `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionStatusResponse) Reset() {
	*x = GetExecutionStatusResponse{}
	mi := &file_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionStatusResponse) ProtoMessage() {}

func (x *GetExecutionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionStatusResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{7}
}

func (x *GetExecutionStatusResponse) GetExecution() *ExecutionResult {
	if x != nil {
		return x.Execution
	}
	return nil
}

func (x *GetExecutionStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetExecutionStatusResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type CancelExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecutionResponse) Reset() {
	*x = CancelExecutionResponse{}
	mi := &file_execution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecutionResponse) ProtoMessage() {}

func (x *CancelExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecutionResponse.ProtoReflect.Descriptor instead.
func (*CancelExecutionResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{8}
}

func (x *CancelExecutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelExecutionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CancelExecutionResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListExecutionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ExecutionResult     `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_execution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{9}
}

func (x *ListExecutionsResponse) GetExecutions() []*ExecutionResult {
	if x != nil {
		return x.Executions
	}
	return nil
}

func (x *ListExecutionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListExecutionsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListExecutionsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListExecutionsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type GetExecutionLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*ExecutionLog        `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionLogsResponse) Reset() {
	*x = GetExecutionLogsResponse{}
	mi := &file_execution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionLogsResponse) ProtoMessage() {}

func (x *GetExecutionLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionLogsResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionLogsResponse) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{10}
}

func (x *GetExecutionLogsResponse) GetLogs() []*ExecutionLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetExecutionLogsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetExecutionLogsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetExecutionLogsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetExecutionLogsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Data Models
type ExecutionResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId          string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkflowId           string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UserId               string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status               string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "completed", "failed", "cancelled"
	StepResults          []*StepResult          `protobuf:"bytes,5,rep,name=step_results,json=stepResults,proto3" json:"step_results,omitempty"`
	Errors               []*ExecutionError      `protobuf:"bytes,6,rep,name=errors,proto3" json:"errors,omitempty"`
	ExecutionTimeSeconds float32                `protobuf:"fixed32,7,opt,name=execution_time_seconds,json=executionTimeSeconds,proto3" json:"execution_time_seconds,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	TestMode             bool                   `protobuf:"varint,10,opt,name=test_mode,json=testMode,proto3" json:"test_mode,omitempty"`
	Metadata             *ExecutionMetadata     `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_execution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionResult) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionResult) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionResult) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExecutionResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionResult) GetStepResults() []*StepResult {
	if x != nil {
		return x.StepResults
	}
	return nil
}

func (x *ExecutionResult) GetErrors() []*ExecutionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ExecutionResult) GetExecutionTimeSeconds() float32 {
	if x != nil {
		return x.ExecutionTimeSeconds
	}
	return 0
}

func (x *ExecutionResult) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ExecutionResult) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ExecutionResult) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

func (x *ExecutionResult) GetMetadata() *ExecutionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StepResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	StepName      string                 `protobuf:"bytes,2,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "waiting", "running", "completed", "failed", "skipped", "retrying"
	Result        *structpb.Struct       `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	ExecutionTime float32                `protobuf:"fixed32,6,opt,name=execution_time,json=executionTime,proto3" json:"execution_time,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RetryCount    int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResult) Reset() {
	*x = StepResult{}
	mi := &file_execution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResult) ProtoMessage() {}

func (x *StepResult) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResult.ProtoReflect.Descriptor instead.
func (*StepResult) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{12}
}

func (x *StepResult) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepResult) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *StepResult) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *StepResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StepResult) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StepResult) GetExecutionTime() float32 {
	if x != nil {
		return x.ExecutionTime
	}
	return 0
}

func (x *StepResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StepResult) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *StepResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecutionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionError) Reset() {
	*x = ExecutionError{}
	mi := &file_execution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionError) ProtoMessage() {}

func (x *ExecutionError) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionError.ProtoReflect.Descriptor instead.
func (*ExecutionError) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{13}
}

func (x *ExecutionError) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionError) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecutionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *ExecutionError) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExecutionError) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type ExecutionLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	StepId        string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	LogData       *structpb.Struct       `protobuf:"bytes,6,opt,name=log_data,json=logData,proto3" json:"log_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionLog) Reset() {
	*x = ExecutionLog{}
	mi := &file_execution_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionLog) ProtoMessage() {}

func (x *ExecutionLog) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionLog.ProtoReflect.Descriptor instead.
func (*ExecutionLog) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{14}
}

func (x *ExecutionLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExecutionLog) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecutionLog) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *ExecutionLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecutionLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionLog) GetLogData() *structpb.Struct {
	if x != nil {
		return x.LogData
	}
	return nil
}

func (x *ExecutionLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ExecutionMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalSteps       int32                  `protobuf:"varint,1,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	CompletedSteps   int32                  `protobuf:"varint,2,opt,name=completed_steps,json=completedSteps,proto3" json:"completed_steps,omitempty"`
	FailedSteps      int32                  `protobuf:"varint,3,opt,name=failed_steps,json=failedSteps,proto3" json:"failed_steps,omitempty"`
	SuccessRate      float32                `protobuf:"fixed32,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	WorkflowMetadata *structpb.Struct       `protobuf:"bytes,5,opt,name=workflow_metadata,json=workflowMetadata,proto3" json:"workflow_metadata,omitempty"`
	ParallelGroups   []string               `protobuf:"bytes,6,rep,name=parallel_groups,json=parallelGroups,proto3" json:"parallel_groups,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionMetadata) Reset() {
	*x = ExecutionMetadata{}
	mi := &file_execution_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMetadata) ProtoMessage() {}

func (x *ExecutionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_execution_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMetadata.ProtoReflect.Descriptor instead.
func (*ExecutionMetadata) Descriptor() ([]byte, []int) {
	return file_execution_proto_rawDescGZIP(), []int{15}
}

func (x *ExecutionMetadata) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ExecutionMetadata) GetCompletedSteps() int32 {
	if x != nil {
		return x.CompletedSteps
	}
	return 0
}

func (x *ExecutionMetadata) GetFailedSteps() int32 {
	if x != nil {
		return x.FailedSteps
	}
	return 0
}

func (x *ExecutionMetadata) GetSuccessRate() float32 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *ExecutionMetadata) GetWorkflowMetadata() *structpb.Struct {
	if x != nil {
		return x.WorkflowMetadata
	}
	return nil
}

func (x *ExecutionMetadata) GetParallelGroups() []string {
	if x != nil {
		return x.ParallelGroups
	}
	return nil
}

var File_execution_proto protoreflect.FileDescriptor

const file_execution_proto_rawDesc = "" +
	"\n" +
	"\x0fexecution.proto\x12\x15verbilio.execution.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xf8\x01\n" +
	"\x16ExecuteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttest_mode\x18\x03 \x01(\bR\btestMode\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x127\n" +
	"\n" +
	"parameters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12'\n" +
	"\x0fstream_progress\x18\x06 \x01(\bR\x0estreamProgress\"~\n" +
	"\x19GetExecutionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\x93\x01\n" +
	"\x16CancelExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xbe\x01\n" +
	"\x15ListExecutionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\"\xaa\x01\n" +
	"\x17GetExecutionLogsRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"\xe6\x01\n" +
	"\x17ExecuteWorkflowResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12D\n" +
	"\bmetadata\x18\x05 \x01(\v2(.ai-workflow-automation.execution.v1.ExecutionMetadataR\bmetadata\"\xde\x02\n" +
	"\x0fExecutionUpdate\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tstep_name\x18\x03 \x01(\tR\bstepName\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12/\n" +
	"\x13progress_percentage\x18\a \x01(\x02R\x12progressPercentage\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04data\x18\t \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\xc6\x01\n" +
	"\x1aGetExecutionStatusResponse\x12D\n" +
	"\texecution\x18\x01 \x01(\v2&.ai-workflow-automation.execution.v1.ExecutionResultR\texecution\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\x97\x01\n" +
	"\x17CancelExecutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xe5\x01\n" +
	"\x16ListExecutionsResponse\x12F\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2&.ai-workflow-automation.execution.v1.ExecutionResultR\n" +
	"executions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xd8\x01\n" +
	"\x18GetExecutionLogsResponse\x127\n" +
	"\x04logs\x18\x01 \x03(\v2#.ai-workflow-automation.execution.v1.ExecutionLogR\x04logs\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x9e\x04\n" +
	"\x0fExecutionResult\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12D\n" +
	"\fstep_results\x18\x05 \x03(\v2!.ai-workflow-automation.execution.v1.StepResultR\vstepResults\x12=\n" +
	"\x06errors\x18\x06 \x03(\v2%.ai-workflow-automation.execution.v1.ExecutionErrorR\x06errors\x124\n" +
	"\x16execution_time_seconds\x18\a \x01(\x02R\x14executionTimeSeconds\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1b\n" +
	"\ttest_mode\x18\n" +
	" \x01(\bR\btestMode\x12D\n" +
	"\bmetadata\x18\v \x01(\v2(.ai-workflow-automation.execution.v1.ExecutionMetadataR\bmetadata\"\xcf\x02\n" +
	"\n" +
	"StepResult\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1b\n" +
	"\tstep_name\x18\x02 \x01(\tR\bstepName\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12/\n" +
	"\x06result\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x06result\x12%\n" +
	"\x0eexecution_time\x18\x06 \x01(\x02R\rexecutionTime\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"\xe5\x01\n" +
	"\x0eExecutionError\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x121\n" +
	"\adetails\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adetails\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\"\xfa\x01\n" +
	"\fExecutionLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x122\n" +
	"\blog_data\x18\x06 \x01(\v2\x17.google.protobuf.StructR\alogData\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x92\x02\n" +
	"\x11ExecutionMetadata\x12\x1f\n" +
	"\vtotal_steps\x18\x01 \x01(\x05R\n" +
	"totalSteps\x12'\n" +
	"\x0fcompleted_steps\x18\x02 \x01(\x05R\x0ecompletedSteps\x12!\n" +
	"\ffailed_steps\x18\x03 \x01(\x05R\vfailedSteps\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x02R\vsuccessRate\x12D\n" +
	"\x11workflow_metadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x10workflowMetadata\x12'\n" +
	"\x0fparallel_groups\x18\x06 \x03(\tR\x0eparallelGroups2\xc9\x05\n" +
	"\x10ExecutionService\x12p\n" +
	"\x0fExecuteWorkflow\x12-.ai-workflow-automation.execution.v1.ExecuteWorkflowRequest\x1a..ai-workflow-automation.execution.v1.ExecuteWorkflowResponse\x12r\n" +
	"\x17StreamWorkflowExecution\x12-.ai-workflow-automation.execution.v1.ExecuteWorkflowRequest\x1a&.ai-workflow-automation.execution.v1.ExecutionUpdate0\x01\x12y\n" +
	"\x12GetExecutionStatus\x120.ai-workflow-automation.execution.v1.GetExecutionStatusRequest\x1a1.ai-workflow-automation.execution.v1.GetExecutionStatusResponse\x12p\n" +
	"\x0fCancelExecution\x12-.ai-workflow-automation.execution.v1.CancelExecutionRequest\x1a..ai-workflow-automation.execution.v1.CancelExecutionResponse\x12m\n" +
	"\x0eListExecutions\x12,.ai-workflow-automation.execution.v1.ListExecutionsRequest\x1a-.ai-workflow-automation.execution.v1.ListExecutionsResponse\x12s\n" +
	"\x10GetExecutionLogs\x12..ai-workflow-automation.execution.v1.GetExecutionLogsRequest\x1a/.ai-workflow-automation.execution.v1.GetExecutionLogsResponseB8Z6github.com/ai-workflow-automation/api-gateway/pkg/grpc_client/protosb\x06proto3"

var (
	file_execution_proto_rawDescOnce sync.Once
	file_execution_proto_rawDescData []byte
)

func file_execution_proto_rawDescGZIP() []byte {
	file_execution_proto_rawDescOnce.Do(func() {
		file_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)))
	})
	return file_execution_proto_rawDescData
}

var file_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_execution_proto_goTypes = []any{
	(*ExecuteWorkflowRequest)(nil),     // 0: ai-workflow-automation.execution.v1.ExecuteWorkflowRequest
	(*GetExecutionStatusRequest)(nil),  // 1: ai-workflow-automation.execution.v1.GetExecutionStatusRequest
	(*CancelExecutionRequest)(nil),     // 2: ai-workflow-automation.execution.v1.CancelExecutionRequest
	(*ListExecutionsRequest)(nil),      // 3: ai-workflow-automation.execution.v1.ListExecutionsRequest
	(*GetExecutionLogsRequest)(nil),    // 4: ai-workflow-automation.execution.v1.GetExecutionLogsRequest
	(*ExecuteWorkflowResponse)(nil),    // 5: ai-workflow-automation.execution.v1.ExecuteWorkflowResponse
	(*ExecutionUpdate)(nil),            // 6: ai-workflow-automation.execution.v1.ExecutionUpdate
	(*GetExecutionStatusResponse)(nil), // 7: ai-workflow-automation.execution.v1.GetExecutionStatusResponse
	(*CancelExecutionResponse)(nil),    // 8: ai-workflow-automation.execution.v1.CancelExecutionResponse
	(*ListExecutionsResponse)(nil),     // 9: ai-workflow-automation.execution.v1.ListExecutionsResponse
	(*GetExecutionLogsResponse)(nil),   // 10: ai-workflow-automation.execution.v1.GetExecutionLogsResponse
	(*ExecutionResult)(nil),            // 11: ai-workflow-automation.execution.v1.ExecutionResult
	(*StepResult)(nil),                 // 12: ai-workflow-automation.execution.v1.StepResult
	(*ExecutionError)(nil),             // 13: ai-workflow-automation.execution.v1.ExecutionError
	(*ExecutionLog)(nil),               // 14: ai-workflow-automation.execution.v1.ExecutionLog
	(*ExecutionMetadata)(nil),          // 15: ai-workflow-automation.execution.v1.ExecutionMetadata
	(*structpb.Struct)(nil),            // 16: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
}
var file_execution_proto_depIdxs = []int32{
	16, // 0: ai-workflow-automation.execution.v1.ExecuteWorkflowRequest.parameters:type_name -> google.protobuf.Struct
	15, // 1: ai-workflow-automation.execution.v1.ExecuteWorkflowResponse.metadata:type_name -> ai-workflow-automation.execution.v1.ExecutionMetadata
	17, // 2: ai-workflow-automation.execution.v1.ExecutionUpdate.timestamp:type_name -> google.protobuf.Timestamp
	16, // 3: ai-workflow-automation.execution.v1.ExecutionUpdate.data:type_name -> google.protobuf.Struct
	11, // 4: ai-workflow-automation.execution.v1.GetExecutionStatusResponse.execution:type_name -> ai-workflow-automation.execution.v1.ExecutionResult
	11, // 5: ai-workflow-automation.execution.v1.ListExecutionsResponse.executions:type_name -> ai-workflow-automation.execution.v1.ExecutionResult
	14, // 6: ai-workflow-automation.execution.v1.GetExecutionLogsResponse.logs:type_name -> ai-workflow-automation.execution.v1.ExecutionLog
	12, // 7: ai-workflow-automation.execution.v1.ExecutionResult.step_results:type_name -> ai-workflow-automation.execution.v1.StepResult
	13, // 8: ai-workflow-automation.execution.v1.ExecutionResult.errors:type_name -> ai-workflow-automation.execution.v1.ExecutionError
	17, // 9: ai-workflow-automation.execution.v1.ExecutionResult.started_at:type_name -> google.protobuf.Timestamp
	17, // 10: ai-workflow-automation.execution.v1.ExecutionResult.completed_at:type_name -> google.protobuf.Timestamp
	15, // 11: ai-workflow-automation.execution.v1.ExecutionResult.metadata:type_name -> ai-workflow-automation.execution.v1.ExecutionMetadata
	16, // 12: ai-workflow-automation.execution.v1.StepResult.result:type_name -> google.protobuf.Struct
	17, // 13: ai-workflow-automation.execution.v1.StepResult.timestamp:type_name -> google.protobuf.Timestamp
	16, // 14: ai-workflow-automation.execution.v1.ExecutionError.details:type_name -> google.protobuf.Struct
	17, // 15: ai-workflow-automation.execution.v1.ExecutionError.timestamp:type_name -> google.protobuf.Timestamp
	16, // 16: ai-workflow-automation.execution.v1.ExecutionLog.log_data:type_name -> google.protobuf.Struct
	17, // 17: ai-workflow-automation.execution.v1.ExecutionLog.timestamp:type_name -> google.protobuf.Timestamp
	16, // 18: ai-workflow-automation.execution.v1.ExecutionMetadata.workflow_metadata:type_name -> google.protobuf.Struct
	0,  // 19: ai-workflow-automation.execution.v1.ExecutionService.ExecuteWorkflow:input_type -> ai-workflow-automation.execution.v1.ExecuteWorkflowRequest
	0,  // 20: ai-workflow-automation.execution.v1.ExecutionService.StreamWorkflowExecution:input_type -> ai-workflow-automation.execution.v1.ExecuteWorkflowRequest
	1,  // 21: ai-workflow-automation.execution.v1.ExecutionService.GetExecutionStatus:input_type -> ai-workflow-automation.execution.v1.GetExecutionStatusRequest
	2,  // 22: ai-workflow-automation.execution.v1.ExecutionService.CancelExecution:input_type -> ai-workflow-automation.execution.v1.CancelExecutionRequest
	3,  // 23: ai-workflow-automation.execution.v1.ExecutionService.ListExecutions:input_type -> ai-workflow-automation.execution.v1.ListExecutionsRequest
	4,  // 24: ai-workflow-automation.execution.v1.ExecutionService.GetExecutionLogs:input_type -> ai-workflow-automation.execution.v1.GetExecutionLogsRequest
	5,  // 25: ai-workflow-automation.execution.v1.ExecutionService.ExecuteWorkflow:output_type -> ai-workflow-automation.execution.v1.ExecuteWorkflowResponse
	6,  // 26: ai-workflow-automation.execution.v1.ExecutionService.StreamWorkflowExecution:output_type -> ai-workflow-automation.execution.v1.ExecutionUpdate
	7,  // 27: ai-workflow-automation.execution.v1.ExecutionService.GetExecutionStatus:output_type -> ai-workflow-automation.execution.v1.GetExecutionStatusResponse
	8,  // 28: ai-workflow-automation.execution.v1.ExecutionService.CancelExecution:output_type -> ai-workflow-automation.execution.v1.CancelExecutionResponse
	9,  // 29: ai-workflow-automation.execution.v1.ExecutionService.ListExecutions:output_type -> ai-workflow-automation.execution.v1.ListExecutionsResponse
	10, // 30: ai-workflow-automation.execution.v1.ExecutionService.GetExecutionLogs:output_type -> ai-workflow-automation.execution.v1.GetExecutionLogsResponse
	25, // [25:31] is the sub-list for method output_type
	19, // [19:25] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_execution_proto_init() }
func file_execution_proto_init() {
	if File_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_execution_proto_rawDesc), len(file_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_execution_proto_goTypes,
		DependencyIndexes: file_execution_proto_depIdxs,
		MessageInfos:      file_execution_proto_msgTypes,
	}.Build()
	File_execution_proto = out.File
	file_execution_proto_goTypes = nil
	file_execution_proto_depIdxs = nil
}
