// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: user.proto

package protos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_INACTIVE    UserStatus = 2
	UserStatus_USER_STATUS_SUSPENDED   UserStatus = 3
	UserStatus_USER_STATUS_PENDING     UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_INACTIVE",
		3: "USER_STATUS_SUSPENDED",
		4: "USER_STATUS_PENDING",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_INACTIVE":    2,
		"USER_STATUS_SUSPENDED":   3,
		"USER_STATUS_PENDING":     4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

type ToolCategory int32

const (
	ToolCategory_TOOL_CATEGORY_UNSPECIFIED   ToolCategory = 0
	ToolCategory_TOOL_CATEGORY_GENERAL       ToolCategory = 1
	ToolCategory_TOOL_CATEGORY_DEVELOPMENT   ToolCategory = 2
	ToolCategory_TOOL_CATEGORY_DATA_ANALYSIS ToolCategory = 3
	ToolCategory_TOOL_CATEGORY_COMMUNICATION ToolCategory = 4
	ToolCategory_TOOL_CATEGORY_PRODUCTIVITY  ToolCategory = 5
	ToolCategory_TOOL_CATEGORY_CUSTOM        ToolCategory = 6
)

// Enum value maps for ToolCategory.
var (
	ToolCategory_name = map[int32]string{
		0: "TOOL_CATEGORY_UNSPECIFIED",
		1: "TOOL_CATEGORY_GENERAL",
		2: "TOOL_CATEGORY_DEVELOPMENT",
		3: "TOOL_CATEGORY_DATA_ANALYSIS",
		4: "TOOL_CATEGORY_COMMUNICATION",
		5: "TOOL_CATEGORY_PRODUCTIVITY",
		6: "TOOL_CATEGORY_CUSTOM",
	}
	ToolCategory_value = map[string]int32{
		"TOOL_CATEGORY_UNSPECIFIED":   0,
		"TOOL_CATEGORY_GENERAL":       1,
		"TOOL_CATEGORY_DEVELOPMENT":   2,
		"TOOL_CATEGORY_DATA_ANALYSIS": 3,
		"TOOL_CATEGORY_COMMUNICATION": 4,
		"TOOL_CATEGORY_PRODUCTIVITY":  5,
		"TOOL_CATEGORY_CUSTOM":        6,
	}
)

func (x ToolCategory) Enum() *ToolCategory {
	p := new(ToolCategory)
	*p = x
	return p
}

func (x ToolCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[1].Descriptor()
}

func (ToolCategory) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[1]
}

func (x ToolCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolCategory.Descriptor instead.
func (ToolCategory) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

type ActivityType int32

const (
	ActivityType_ACTIVITY_TYPE_UNSPECIFIED         ActivityType = 0
	ActivityType_ACTIVITY_TYPE_LOGIN               ActivityType = 1
	ActivityType_ACTIVITY_TYPE_LOGOUT              ActivityType = 2
	ActivityType_ACTIVITY_TYPE_WORKFLOW_CREATED    ActivityType = 3
	ActivityType_ACTIVITY_TYPE_WORKFLOW_EXECUTED   ActivityType = 4
	ActivityType_ACTIVITY_TYPE_TOOL_REGISTERED     ActivityType = 5
	ActivityType_ACTIVITY_TYPE_TOOL_USED           ActivityType = 6
	ActivityType_ACTIVITY_TYPE_PREFERENCES_UPDATED ActivityType = 7
	ActivityType_ACTIVITY_TYPE_ERROR_OCCURRED      ActivityType = 8
)

// Enum value maps for ActivityType.
var (
	ActivityType_name = map[int32]string{
		0: "ACTIVITY_TYPE_UNSPECIFIED",
		1: "ACTIVITY_TYPE_LOGIN",
		2: "ACTIVITY_TYPE_LOGOUT",
		3: "ACTIVITY_TYPE_WORKFLOW_CREATED",
		4: "ACTIVITY_TYPE_WORKFLOW_EXECUTED",
		5: "ACTIVITY_TYPE_TOOL_REGISTERED",
		6: "ACTIVITY_TYPE_TOOL_USED",
		7: "ACTIVITY_TYPE_PREFERENCES_UPDATED",
		8: "ACTIVITY_TYPE_ERROR_OCCURRED",
	}
	ActivityType_value = map[string]int32{
		"ACTIVITY_TYPE_UNSPECIFIED":         0,
		"ACTIVITY_TYPE_LOGIN":               1,
		"ACTIVITY_TYPE_LOGOUT":              2,
		"ACTIVITY_TYPE_WORKFLOW_CREATED":    3,
		"ACTIVITY_TYPE_WORKFLOW_EXECUTED":   4,
		"ACTIVITY_TYPE_TOOL_REGISTERED":     5,
		"ACTIVITY_TYPE_TOOL_USED":           6,
		"ACTIVITY_TYPE_PREFERENCES_UPDATED": 7,
		"ACTIVITY_TYPE_ERROR_OCCURRED":      8,
	}
)

func (x ActivityType) Enum() *ActivityType {
	p := new(ActivityType)
	*p = x
	return p
}

func (x ActivityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_proto_enumTypes[2].Descriptor()
}

func (ActivityType) Type() protoreflect.EnumType {
	return &file_user_proto_enumTypes[2]
}

func (x ActivityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityType.Descriptor instead.
func (ActivityType) EnumDescriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

type GetUserProfileRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludePreferences bool                   `protobuf:"varint,2,opt,name=include_preferences,json=includePreferences,proto3" json:"include_preferences,omitempty"`
	IncludeTools       bool                   `protobuf:"varint,3,opt,name=include_tools,json=includeTools,proto3" json:"include_tools,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProfileRequest) GetIncludePreferences() bool {
	if x != nil {
		return x.IncludePreferences
	}
	return false
}

func (x *GetUserProfileRequest) GetIncludeTools() bool {
	if x != nil {
		return x.IncludeTools
	}
	return false
}

type UpdateUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Preferences   *UserPreferences       `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	MergeMode     bool                   `protobuf:"varint,3,opt,name=merge_mode,json=mergeMode,proto3" json:"merge_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPreferencesRequest) Reset() {
	*x = UpdateUserPreferencesRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesRequest) ProtoMessage() {}

func (x *UpdateUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserPreferencesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserPreferencesRequest) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UpdateUserPreferencesRequest) GetMergeMode() bool {
	if x != nil {
		return x.MergeMode
	}
	return false
}

type GetUserContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextKeys   []string               `protobuf:"bytes,3,rep,name=context_keys,json=contextKeys,proto3" json:"context_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContextRequest) Reset() {
	*x = GetUserContextRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContextRequest) ProtoMessage() {}

func (x *GetUserContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContextRequest.ProtoReflect.Descriptor instead.
func (*GetUserContextRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUserContextRequest) GetContextKeys() []string {
	if x != nil {
		return x.ContextKeys
	}
	return nil
}

type UpdateUserContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ContextUpdates *structpb.Struct       `protobuf:"bytes,3,opt,name=context_updates,json=contextUpdates,proto3" json:"context_updates,omitempty"`
	MergeMode      bool                   `protobuf:"varint,4,opt,name=merge_mode,json=mergeMode,proto3" json:"merge_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserContextRequest) Reset() {
	*x = UpdateUserContextRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserContextRequest) ProtoMessage() {}

func (x *UpdateUserContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserContextRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UpdateUserContextRequest) GetContextUpdates() *structpb.Struct {
	if x != nil {
		return x.ContextUpdates
	}
	return nil
}

func (x *UpdateUserContextRequest) GetMergeMode() bool {
	if x != nil {
		return x.MergeMode
	}
	return false
}

type GetUserToolsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category        ToolCategory           `protobuf:"varint,2,opt,name=category,proto3,enum=ai-workflow-automation.user.ToolCategory" json:"category,omitempty"`
	IncludeDisabled bool                   `protobuf:"varint,3,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserToolsRequest) Reset() {
	*x = GetUserToolsRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserToolsRequest) ProtoMessage() {}

func (x *GetUserToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserToolsRequest.ProtoReflect.Descriptor instead.
func (*GetUserToolsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserToolsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserToolsRequest) GetCategory() ToolCategory {
	if x != nil {
		return x.Category
	}
	return ToolCategory_TOOL_CATEGORY_UNSPECIFIED
}

func (x *GetUserToolsRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type RegisterUserToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tool          *UserTool              `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	AutoEnable    bool                   `protobuf:"varint,3,opt,name=auto_enable,json=autoEnable,proto3" json:"auto_enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserToolRequest) Reset() {
	*x = RegisterUserToolRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserToolRequest) ProtoMessage() {}

func (x *RegisterUserToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserToolRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserToolRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterUserToolRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserToolRequest) GetTool() *UserTool {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *RegisterUserToolRequest) GetAutoEnable() bool {
	if x != nil {
		return x.AutoEnable
	}
	return false
}

type GetUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	ActivityType  ActivityType           `protobuf:"varint,4,opt,name=activity_type,json=activityType,proto3,enum=ai-workflow-automation.user.ActivityType" json:"activity_type,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityRequest) Reset() {
	*x = GetUserActivityRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityRequest) ProtoMessage() {}

func (x *GetUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserActivityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserActivityRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetUserActivityRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *GetUserActivityRequest) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *GetUserActivityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Preferences   *UserPreferences       `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Tools         []*UserTool            `protobuf:"bytes,3,rep,name=tools,proto3" json:"tools,omitempty"`
	Status        UserStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=ai-workflow-automation.user.UserStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetUserProfileResponse) GetPreferences() *UserPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *GetUserProfileResponse) GetTools() []*UserTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetUserProfileResponse) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

type UpdateUserPreferencesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UpdatedPreferences *UserPreferences       `protobuf:"bytes,1,opt,name=updated_preferences,json=updatedPreferences,proto3" json:"updated_preferences,omitempty"`
	Success            bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message            string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateUserPreferencesResponse) Reset() {
	*x = UpdateUserPreferencesResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPreferencesResponse) ProtoMessage() {}

func (x *UpdateUserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserPreferencesResponse) GetUpdatedPreferences() *UserPreferences {
	if x != nil {
		return x.UpdatedPreferences
	}
	return nil
}

func (x *UpdateUserPreferencesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserPreferencesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *structpb.Struct       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserContextResponse) Reset() {
	*x = GetUserContextResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserContextResponse) ProtoMessage() {}

func (x *GetUserContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserContextResponse.ProtoReflect.Descriptor instead.
func (*GetUserContextResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserContextResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetUserContextResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetUserContextResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type UpdateUserContextResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedContext *structpb.Struct       `protobuf:"bytes,1,opt,name=updated_context,json=updatedContext,proto3" json:"updated_context,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateUserContextResponse) Reset() {
	*x = UpdateUserContextResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserContextResponse) ProtoMessage() {}

func (x *UpdateUserContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserContextResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserContextResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserContextResponse) GetUpdatedContext() *structpb.Struct {
	if x != nil {
		return x.UpdatedContext
	}
	return nil
}

func (x *UpdateUserContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateUserContextResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserToolsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Tools               []*UserTool            `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	TotalCount          int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	AvailableCategories []ToolCategory         `protobuf:"varint,3,rep,packed,name=available_categories,json=availableCategories,proto3,enum=ai-workflow-automation.user.ToolCategory" json:"available_categories,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetUserToolsResponse) Reset() {
	*x = GetUserToolsResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserToolsResponse) ProtoMessage() {}

func (x *GetUserToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserToolsResponse.ProtoReflect.Descriptor instead.
func (*GetUserToolsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserToolsResponse) GetTools() []*UserTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetUserToolsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetUserToolsResponse) GetAvailableCategories() []ToolCategory {
	if x != nil {
		return x.AvailableCategories
	}
	return nil
}

type RegisterUserToolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegisteredTool *UserTool              `protobuf:"bytes,1,opt,name=registered_tool,json=registeredTool,proto3" json:"registered_tool,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	ToolId         string                 `protobuf:"bytes,4,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterUserToolResponse) Reset() {
	*x = RegisterUserToolResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserToolResponse) ProtoMessage() {}

func (x *RegisterUserToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserToolResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserToolResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterUserToolResponse) GetRegisteredTool() *UserTool {
	if x != nil {
		return x.RegisteredTool
	}
	return nil
}

func (x *RegisterUserToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterUserToolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterUserToolResponse) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type GetUserActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activities    []*UserActivity        `protobuf:"bytes,1,rep,name=activities,proto3" json:"activities,omitempty"`
	Metrics       *UserMetrics           `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivityResponse) Reset() {
	*x = GetUserActivityResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivityResponse) ProtoMessage() {}

func (x *GetUserActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivityResponse.ProtoReflect.Descriptor instead.
func (*GetUserActivityResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserActivityResponse) GetActivities() []*UserActivity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *GetUserActivityResponse) GetMetrics() *UserMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetUserActivityResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetUserActivityResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastActive    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Status        UserStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=ai-workflow-automation.user.UserStatus" json:"status,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetLastActive() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActive
	}
	return nil
}

func (x *UserProfile) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *UserProfile) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UserPreferences struct {
	state                   protoimpl.MessageState   `protogen:"open.v1"`
	Language                *LanguagePreference      `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	UiPreferences           *UIPreferences           `protobuf:"bytes,2,opt,name=ui_preferences,json=uiPreferences,proto3" json:"ui_preferences,omitempty"`
	WorkflowPreferences     *WorkflowPreferences     `protobuf:"bytes,3,opt,name=workflow_preferences,json=workflowPreferences,proto3" json:"workflow_preferences,omitempty"`
	NotificationPreferences *NotificationPreferences `protobuf:"bytes,4,opt,name=notification_preferences,json=notificationPreferences,proto3" json:"notification_preferences,omitempty"`
	SecurityPreferences     *SecurityPreferences     `protobuf:"bytes,5,opt,name=security_preferences,json=securityPreferences,proto3" json:"security_preferences,omitempty"`
	CustomPreferences       *structpb.Struct         `protobuf:"bytes,6,opt,name=custom_preferences,json=customPreferences,proto3" json:"custom_preferences,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UserPreferences) Reset() {
	*x = UserPreferences{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferences) ProtoMessage() {}

func (x *UserPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferences.ProtoReflect.Descriptor instead.
func (*UserPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserPreferences) GetLanguage() *LanguagePreference {
	if x != nil {
		return x.Language
	}
	return nil
}

func (x *UserPreferences) GetUiPreferences() *UIPreferences {
	if x != nil {
		return x.UiPreferences
	}
	return nil
}

func (x *UserPreferences) GetWorkflowPreferences() *WorkflowPreferences {
	if x != nil {
		return x.WorkflowPreferences
	}
	return nil
}

func (x *UserPreferences) GetNotificationPreferences() *NotificationPreferences {
	if x != nil {
		return x.NotificationPreferences
	}
	return nil
}

func (x *UserPreferences) GetSecurityPreferences() *SecurityPreferences {
	if x != nil {
		return x.SecurityPreferences
	}
	return nil
}

func (x *UserPreferences) GetCustomPreferences() *structpb.Struct {
	if x != nil {
		return x.CustomPreferences
	}
	return nil
}

type UIPreferences struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Theme            string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Layout           string                 `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	EnableAnimations bool                   `protobuf:"varint,3,opt,name=enable_animations,json=enableAnimations,proto3" json:"enable_animations,omitempty"`
	ItemsPerPage     int32                  `protobuf:"varint,4,opt,name=items_per_page,json=itemsPerPage,proto3" json:"items_per_page,omitempty"`
	FavoriteTools    []string               `protobuf:"bytes,5,rep,name=favorite_tools,json=favoriteTools,proto3" json:"favorite_tools,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UIPreferences) Reset() {
	*x = UIPreferences{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIPreferences) ProtoMessage() {}

func (x *UIPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIPreferences.ProtoReflect.Descriptor instead.
func (*UIPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UIPreferences) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UIPreferences) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *UIPreferences) GetEnableAnimations() bool {
	if x != nil {
		return x.EnableAnimations
	}
	return false
}

func (x *UIPreferences) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

func (x *UIPreferences) GetFavoriteTools() []string {
	if x != nil {
		return x.FavoriteTools
	}
	return nil
}

type WorkflowPreferences struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AutoSaveWorkflows     bool                   `protobuf:"varint,1,opt,name=auto_save_workflows,json=autoSaveWorkflows,proto3" json:"auto_save_workflows,omitempty"`
	DefaultTimeoutSeconds int32                  `protobuf:"varint,2,opt,name=default_timeout_seconds,json=defaultTimeoutSeconds,proto3" json:"default_timeout_seconds,omitempty"`
	EnableStreaming       bool                   `protobuf:"varint,3,opt,name=enable_streaming,json=enableStreaming,proto3" json:"enable_streaming,omitempty"`
	DefaultModel          string                 `protobuf:"bytes,4,opt,name=default_model,json=defaultModel,proto3" json:"default_model,omitempty"`
	PreferredTools        []string               `protobuf:"bytes,5,rep,name=preferred_tools,json=preferredTools,proto3" json:"preferred_tools,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WorkflowPreferences) Reset() {
	*x = WorkflowPreferences{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPreferences) ProtoMessage() {}

func (x *WorkflowPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPreferences.ProtoReflect.Descriptor instead.
func (*WorkflowPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *WorkflowPreferences) GetAutoSaveWorkflows() bool {
	if x != nil {
		return x.AutoSaveWorkflows
	}
	return false
}

func (x *WorkflowPreferences) GetDefaultTimeoutSeconds() int32 {
	if x != nil {
		return x.DefaultTimeoutSeconds
	}
	return 0
}

func (x *WorkflowPreferences) GetEnableStreaming() bool {
	if x != nil {
		return x.EnableStreaming
	}
	return false
}

func (x *WorkflowPreferences) GetDefaultModel() string {
	if x != nil {
		return x.DefaultModel
	}
	return ""
}

func (x *WorkflowPreferences) GetPreferredTools() []string {
	if x != nil {
		return x.PreferredTools
	}
	return nil
}

type NotificationPreferences struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EmailNotifications   bool                   `protobuf:"varint,1,opt,name=email_notifications,json=emailNotifications,proto3" json:"email_notifications,omitempty"`
	PushNotifications    bool                   `protobuf:"varint,2,opt,name=push_notifications,json=pushNotifications,proto3" json:"push_notifications,omitempty"`
	WorkflowCompletion   bool                   `protobuf:"varint,3,opt,name=workflow_completion,json=workflowCompletion,proto3" json:"workflow_completion,omitempty"`
	ErrorAlerts          bool                   `protobuf:"varint,4,opt,name=error_alerts,json=errorAlerts,proto3" json:"error_alerts,omitempty"`
	NotificationChannels []string               `protobuf:"bytes,5,rep,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *NotificationPreferences) GetEmailNotifications() bool {
	if x != nil {
		return x.EmailNotifications
	}
	return false
}

func (x *NotificationPreferences) GetPushNotifications() bool {
	if x != nil {
		return x.PushNotifications
	}
	return false
}

func (x *NotificationPreferences) GetWorkflowCompletion() bool {
	if x != nil {
		return x.WorkflowCompletion
	}
	return false
}

func (x *NotificationPreferences) GetErrorAlerts() bool {
	if x != nil {
		return x.ErrorAlerts
	}
	return false
}

func (x *NotificationPreferences) GetNotificationChannels() []string {
	if x != nil {
		return x.NotificationChannels
	}
	return nil
}

type SecurityPreferences struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequireMfa            bool                   `protobuf:"varint,1,opt,name=require_mfa,json=requireMfa,proto3" json:"require_mfa,omitempty"`
	SessionTimeoutMinutes int32                  `protobuf:"varint,2,opt,name=session_timeout_minutes,json=sessionTimeoutMinutes,proto3" json:"session_timeout_minutes,omitempty"`
	AllowToolRegistration bool                   `protobuf:"varint,3,opt,name=allow_tool_registration,json=allowToolRegistration,proto3" json:"allow_tool_registration,omitempty"`
	TrustedDomains        []string               `protobuf:"bytes,4,rep,name=trusted_domains,json=trustedDomains,proto3" json:"trusted_domains,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SecurityPreferences) Reset() {
	*x = SecurityPreferences{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityPreferences) ProtoMessage() {}

func (x *SecurityPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityPreferences.ProtoReflect.Descriptor instead.
func (*SecurityPreferences) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *SecurityPreferences) GetRequireMfa() bool {
	if x != nil {
		return x.RequireMfa
	}
	return false
}

func (x *SecurityPreferences) GetSessionTimeoutMinutes() int32 {
	if x != nil {
		return x.SessionTimeoutMinutes
	}
	return 0
}

func (x *SecurityPreferences) GetAllowToolRegistration() bool {
	if x != nil {
		return x.AllowToolRegistration
	}
	return false
}

func (x *SecurityPreferences) GetTrustedDomains() []string {
	if x != nil {
		return x.TrustedDomains
	}
	return nil
}

type UserTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      ToolCategory           `protobuf:"varint,4,opt,name=category,proto3,enum=ai-workflow-automation.user.ToolCategory" json:"category,omitempty"`
	Configuration *structpb.Struct       `protobuf:"bytes,5,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	UsageCount    int32                  `protobuf:"varint,9,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTool) Reset() {
	*x = UserTool{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTool) ProtoMessage() {}

func (x *UserTool) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTool.ProtoReflect.Descriptor instead.
func (*UserTool) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *UserTool) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

func (x *UserTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserTool) GetCategory() ToolCategory {
	if x != nil {
		return x.Category
	}
	return ToolCategory_TOOL_CATEGORY_UNSPECIFIED
}

func (x *UserTool) GetConfiguration() *structpb.Struct {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *UserTool) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserTool) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

func (x *UserTool) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *UserTool) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

type UserActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    string                 `protobuf:"bytes,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActivityType  ActivityType           `protobuf:"varint,3,opt,name=activity_type,json=activityType,proto3,enum=ai-workflow-automation.user.ActivityType" json:"activity_type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *UserActivity) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

func (x *UserActivity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserActivity) GetActivityType() ActivityType {
	if x != nil {
		return x.ActivityType
	}
	return ActivityType_ACTIVITY_TYPE_UNSPECIFIED
}

func (x *UserActivity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserActivity) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *UserActivity) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *UserActivity) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type UserMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalWorkflows  int32                  `protobuf:"varint,1,opt,name=total_workflows,json=totalWorkflows,proto3" json:"total_workflows,omitempty"`
	TotalExecutions int32                  `protobuf:"varint,2,opt,name=total_executions,json=totalExecutions,proto3" json:"total_executions,omitempty"`
	TotalToolCalls  int32                  `protobuf:"varint,3,opt,name=total_tool_calls,json=totalToolCalls,proto3" json:"total_tool_calls,omitempty"`
	FirstActivity   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_activity,json=firstActivity,proto3" json:"first_activity,omitempty"`
	LastActivity    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	ActiveSessions  int32                  `protobuf:"varint,6,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	ToolUsage       []*ToolUsage           `protobuf:"bytes,7,rep,name=tool_usage,json=toolUsage,proto3" json:"tool_usage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserMetrics) Reset() {
	*x = UserMetrics{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMetrics) ProtoMessage() {}

func (x *UserMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMetrics.ProtoReflect.Descriptor instead.
func (*UserMetrics) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *UserMetrics) GetTotalWorkflows() int32 {
	if x != nil {
		return x.TotalWorkflows
	}
	return 0
}

func (x *UserMetrics) GetTotalExecutions() int32 {
	if x != nil {
		return x.TotalExecutions
	}
	return 0
}

func (x *UserMetrics) GetTotalToolCalls() int32 {
	if x != nil {
		return x.TotalToolCalls
	}
	return 0
}

func (x *UserMetrics) GetFirstActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstActivity
	}
	return nil
}

func (x *UserMetrics) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *UserMetrics) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *UserMetrics) GetToolUsage() []*ToolUsage {
	if x != nil {
		return x.ToolUsage
	}
	return nil
}

type ToolUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	UsageCount    int32                  `protobuf:"varint,2,opt,name=usage_count,json=usageCount,proto3" json:"usage_count,omitempty"`
	LastUsed      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	SuccessRate   float64                `protobuf:"fixed64,4,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUsage) Reset() {
	*x = ToolUsage{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUsage) ProtoMessage() {}

func (x *ToolUsage) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUsage.ProtoReflect.Descriptor instead.
func (*ToolUsage) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ToolUsage) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolUsage) GetUsageCount() int32 {
	if x != nil {
		return x.UsageCount
	}
	return 0
}

func (x *ToolUsage) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *ToolUsage) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

type LanguagePreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguagePreference) Reset() {
	*x = LanguagePreference{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguagePreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguagePreference) ProtoMessage() {}

func (x *LanguagePreference) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguagePreference.ProtoReflect.Descriptor instead.
func (*LanguagePreference) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *LanguagePreference) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LanguagePreference) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LanguagePreference) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\rverbilio.user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x13include_preferences\x18\x02 \x01(\bR\x12includePreferences\x12#\n" +
	"\rinclude_tools\x18\x03 \x01(\bR\fincludeTools\"\x98\x01\n" +
	"\x1cUpdateUserPreferencesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12@\n" +
	"\vpreferences\x18\x02 \x01(\v2\x1e.ai-workflow-automation.user.UserPreferencesR\vpreferences\x12\x1d\n" +
	"\n" +
	"merge_mode\x18\x03 \x01(\bR\tmergeMode\"r\n" +
	"\x15GetUserContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fcontext_keys\x18\x03 \x03(\tR\vcontextKeys\"\xb3\x01\n" +
	"\x18UpdateUserContextRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12@\n" +
	"\x0fcontext_updates\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x0econtextUpdates\x12\x1d\n" +
	"\n" +
	"merge_mode\x18\x04 \x01(\bR\tmergeMode\"\x92\x01\n" +
	"\x13GetUserToolsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x127\n" +
	"\bcategory\x18\x02 \x01(\x0e2\x1b.ai-workflow-automation.user.ToolCategoryR\bcategory\x12)\n" +
	"\x10include_disabled\x18\x03 \x01(\bR\x0fincludeDisabled\"\x80\x01\n" +
	"\x17RegisterUserToolRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x04tool\x18\x02 \x01(\v2\x17.ai-workflow-automation.user.UserToolR\x04tool\x12\x1f\n" +
	"\vauto_enable\x18\x03 \x01(\bR\n" +
	"autoEnable\"\xfb\x01\n" +
	"\x16GetUserActivityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12@\n" +
	"\ractivity_type\x18\x04 \x01(\x0e2\x1b.ai-workflow-automation.user.ActivityTypeR\factivityType\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xf2\x01\n" +
	"\x16GetUserProfileResponse\x124\n" +
	"\aprofile\x18\x01 \x01(\v2\x1a.ai-workflow-automation.user.UserProfileR\aprofile\x12@\n" +
	"\vpreferences\x18\x02 \x01(\v2\x1e.ai-workflow-automation.user.UserPreferencesR\vpreferences\x12-\n" +
	"\x05tools\x18\x03 \x03(\v2\x17.ai-workflow-automation.user.UserToolR\x05tools\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.ai-workflow-automation.user.UserStatusR\x06status\"\xa4\x01\n" +
	"\x1dUpdateUserPreferencesResponse\x12O\n" +
	"\x13updated_preferences\x18\x01 \x01(\v2\x1e.ai-workflow-automation.user.UserPreferencesR\x12updatedPreferences\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xa9\x01\n" +
	"\x16GetUserContextResponse\x121\n" +
	"\acontext\x18\x01 \x01(\v2\x17.google.protobuf.StructR\acontext\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x91\x01\n" +
	"\x19UpdateUserContextResponse\x12@\n" +
	"\x0fupdated_context\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x0eupdatedContext\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb6\x01\n" +
	"\x14GetUserToolsResponse\x12-\n" +
	"\x05tools\x18\x01 \x03(\v2\x17.ai-workflow-automation.user.UserToolR\x05tools\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12N\n" +
	"\x14available_categories\x18\x03 \x03(\x0e2\x1b.ai-workflow-automation.user.ToolCategoryR\x13availableCategories\"\xa9\x01\n" +
	"\x18RegisterUserToolResponse\x12@\n" +
	"\x0fregistered_tool\x18\x01 \x01(\v2\x17.ai-workflow-automation.user.UserToolR\x0eregisteredTool\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x17\n" +
	"\atool_id\x18\x04 \x01(\tR\x06toolId\"\xc8\x01\n" +
	"\x17GetUserActivityResponse\x12;\n" +
	"\n" +
	"activities\x18\x01 \x03(\v2\x1b.ai-workflow-automation.user.UserActivityR\n" +
	"activities\x124\n" +
	"\ametrics\x18\x02 \x01(\v2\x1a.ai-workflow-automation.user.UserMetricsR\ametrics\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"\xde\x02\n" +
	"\vUserProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vlast_active\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastActive\x121\n" +
	"\x06status\x18\a \x01(\x0e2\x19.ai-workflow-automation.user.UserStatusR\x06status\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xee\x03\n" +
	"\x0fUserPreferences\x12=\n" +
	"\blanguage\x18\x01 \x01(\v2!.ai-workflow-automation.user.LanguagePreferenceR\blanguage\x12C\n" +
	"\x0eui_preferences\x18\x02 \x01(\v2\x1c.ai-workflow-automation.user.UIPreferencesR\ruiPreferences\x12U\n" +
	"\x14workflow_preferences\x18\x03 \x01(\v2\".ai-workflow-automation.user.WorkflowPreferencesR\x13workflowPreferences\x12a\n" +
	"\x18notification_preferences\x18\x04 \x01(\v2&.ai-workflow-automation.user.NotificationPreferencesR\x17notificationPreferences\x12U\n" +
	"\x14security_preferences\x18\x05 \x01(\v2\".ai-workflow-automation.user.SecurityPreferencesR\x13securityPreferences\x12F\n" +
	"\x12custom_preferences\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x11customPreferences\"\xb7\x01\n" +
	"\rUIPreferences\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x16\n" +
	"\x06layout\x18\x02 \x01(\tR\x06layout\x12+\n" +
	"\x11enable_animations\x18\x03 \x01(\bR\x10enableAnimations\x12$\n" +
	"\x0eitems_per_page\x18\x04 \x01(\x05R\fitemsPerPage\x12%\n" +
	"\x0efavorite_tools\x18\x05 \x03(\tR\rfavoriteTools\"\xf6\x01\n" +
	"\x13WorkflowPreferences\x12.\n" +
	"\x13auto_save_workflows\x18\x01 \x01(\bR\x11autoSaveWorkflows\x126\n" +
	"\x17default_timeout_seconds\x18\x02 \x01(\x05R\x15defaultTimeoutSeconds\x12)\n" +
	"\x10enable_streaming\x18\x03 \x01(\bR\x0fenableStreaming\x12#\n" +
	"\rdefault_model\x18\x04 \x01(\tR\fdefaultModel\x12'\n" +
	"\x0fpreferred_tools\x18\x05 \x03(\tR\x0epreferredTools\"\x82\x02\n" +
	"\x17NotificationPreferences\x12/\n" +
	"\x13email_notifications\x18\x01 \x01(\bR\x12emailNotifications\x12-\n" +
	"\x12push_notifications\x18\x02 \x01(\bR\x11pushNotifications\x12/\n" +
	"\x13workflow_completion\x18\x03 \x01(\bR\x12workflowCompletion\x12!\n" +
	"\ferror_alerts\x18\x04 \x01(\bR\verrorAlerts\x123\n" +
	"\x15notification_channels\x18\x05 \x03(\tR\x14notificationChannels\"\xcf\x01\n" +
	"\x13SecurityPreferences\x12\x1f\n" +
	"\vrequire_mfa\x18\x01 \x01(\bR\n" +
	"requireMfa\x126\n" +
	"\x17session_timeout_minutes\x18\x02 \x01(\x05R\x15sessionTimeoutMinutes\x126\n" +
	"\x17allow_tool_registration\x18\x03 \x01(\bR\x15allowToolRegistration\x12'\n" +
	"\x0ftrusted_domains\x18\x04 \x03(\tR\x0etrustedDomains\"\x86\x03\n" +
	"\bUserTool\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1b.ai-workflow-automation.user.ToolCategoryR\bcategory\x12=\n" +
	"\rconfiguration\x18\x05 \x01(\v2\x17.google.protobuf.StructR\rconfiguration\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\x127\n" +
	"\tlast_used\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12\x1f\n" +
	"\vusage_count\x18\t \x01(\x05R\n" +
	"usageCount\"\xb8\x02\n" +
	"\fUserActivity\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\tR\n" +
	"activityId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12@\n" +
	"\ractivity_type\x18\x03 \x01(\x0e2\x1b.ai-workflow-automation.user.ActivityTypeR\factivityType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x121\n" +
	"\adetails\x18\x05 \x01(\v2\x17.google.protobuf.StructR\adetails\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"\xf1\x02\n" +
	"\vUserMetrics\x12'\n" +
	"\x0ftotal_workflows\x18\x01 \x01(\x05R\x0etotalWorkflows\x12)\n" +
	"\x10total_executions\x18\x02 \x01(\x05R\x0ftotalExecutions\x12(\n" +
	"\x10total_tool_calls\x18\x03 \x01(\x05R\x0etotalToolCalls\x12A\n" +
	"\x0efirst_activity\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rfirstActivity\x12?\n" +
	"\rlast_activity\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12'\n" +
	"\x0factive_sessions\x18\x06 \x01(\x05R\x0eactiveSessions\x127\n" +
	"\n" +
	"tool_usage\x18\a \x03(\v2\x18.ai-workflow-automation.user.ToolUsageR\ttoolUsage\"\xa5\x01\n" +
	"\tToolUsage\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1f\n" +
	"\vusage_count\x18\x02 \x01(\x05R\n" +
	"usageCount\x127\n" +
	"\tlast_used\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12!\n" +
	"\fsuccess_rate\x18\x04 \x01(\x01R\vsuccessRate\"j\n" +
	"\x12LanguagePreference\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault*\x8f\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14USER_STATUS_INACTIVE\x10\x02\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\x03\x12\x17\n" +
	"\x13USER_STATUS_PENDING\x10\x04*\xe3\x01\n" +
	"\fToolCategory\x12\x1d\n" +
	"\x19TOOL_CATEGORY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TOOL_CATEGORY_GENERAL\x10\x01\x12\x1d\n" +
	"\x19TOOL_CATEGORY_DEVELOPMENT\x10\x02\x12\x1f\n" +
	"\x1bTOOL_CATEGORY_DATA_ANALYSIS\x10\x03\x12\x1f\n" +
	"\x1bTOOL_CATEGORY_COMMUNICATION\x10\x04\x12\x1e\n" +
	"\x1aTOOL_CATEGORY_PRODUCTIVITY\x10\x05\x12\x18\n" +
	"\x14TOOL_CATEGORY_CUSTOM\x10\x06*\xb2\x02\n" +
	"\fActivityType\x12\x1d\n" +
	"\x19ACTIVITY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ACTIVITY_TYPE_LOGIN\x10\x01\x12\x18\n" +
	"\x14ACTIVITY_TYPE_LOGOUT\x10\x02\x12\"\n" +
	"\x1eACTIVITY_TYPE_WORKFLOW_CREATED\x10\x03\x12#\n" +
	"\x1fACTIVITY_TYPE_WORKFLOW_EXECUTED\x10\x04\x12!\n" +
	"\x1dACTIVITY_TYPE_TOOL_REGISTERED\x10\x05\x12\x1b\n" +
	"\x17ACTIVITY_TYPE_TOOL_USED\x10\x06\x12%\n" +
	"!ACTIVITY_TYPE_PREFERENCES_UPDATED\x10\a\x12 \n" +
	"\x1cACTIVITY_TYPE_ERROR_OCCURRED\x10\b2\xc7\x05\n" +
	"\vUserService\x12]\n" +
	"\x0eGetUserProfile\x12$.ai-workflow-automation.user.GetUserProfileRequest\x1a%.ai-workflow-automation.user.GetUserProfileResponse\x12r\n" +
	"\x15UpdateUserPreferences\x12+.ai-workflow-automation.user.UpdateUserPreferencesRequest\x1a,.ai-workflow-automation.user.UpdateUserPreferencesResponse\x12]\n" +
	"\x0eGetUserContext\x12$.ai-workflow-automation.user.GetUserContextRequest\x1a%.ai-workflow-automation.user.GetUserContextResponse\x12f\n" +
	"\x11UpdateUserContext\x12'.ai-workflow-automation.user.UpdateUserContextRequest\x1a(.ai-workflow-automation.user.UpdateUserContextResponse\x12W\n" +
	"\fGetUserTools\x12\".ai-workflow-automation.user.GetUserToolsRequest\x1a#.ai-workflow-automation.user.GetUserToolsResponse\x12c\n" +
	"\x10RegisterUserTool\x12&.ai-workflow-automation.user.RegisterUserToolRequest\x1a'.ai-workflow-automation.user.RegisterUserToolResponse\x12`\n" +
	"\x0fGetUserActivity\x12%.ai-workflow-automation.user.GetUserActivityRequest\x1a&.ai-workflow-automation.user.GetUserActivityResponseB8Z6github.com/ai-workflow-automation/api-gateway/pkg/grpc_client/protosb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_user_proto_goTypes = []any{
	(UserStatus)(0),                       // 0: ai-workflow-automation.user.UserStatus
	(ToolCategory)(0),                     // 1: ai-workflow-automation.user.ToolCategory
	(ActivityType)(0),                     // 2: ai-workflow-automation.user.ActivityType
	(*GetUserProfileRequest)(nil),         // 3: ai-workflow-automation.user.GetUserProfileRequest
	(*UpdateUserPreferencesRequest)(nil),  // 4: ai-workflow-automation.user.UpdateUserPreferencesRequest
	(*GetUserContextRequest)(nil),         // 5: ai-workflow-automation.user.GetUserContextRequest
	(*UpdateUserContextRequest)(nil),      // 6: ai-workflow-automation.user.UpdateUserContextRequest
	(*GetUserToolsRequest)(nil),           // 7: ai-workflow-automation.user.GetUserToolsRequest
	(*RegisterUserToolRequest)(nil),       // 8: ai-workflow-automation.user.RegisterUserToolRequest
	(*GetUserActivityRequest)(nil),        // 9: ai-workflow-automation.user.GetUserActivityRequest
	(*GetUserProfileResponse)(nil),        // 10: ai-workflow-automation.user.GetUserProfileResponse
	(*UpdateUserPreferencesResponse)(nil), // 11: ai-workflow-automation.user.UpdateUserPreferencesResponse
	(*GetUserContextResponse)(nil),        // 12: ai-workflow-automation.user.GetUserContextResponse
	(*UpdateUserContextResponse)(nil),     // 13: ai-workflow-automation.user.UpdateUserContextResponse
	(*GetUserToolsResponse)(nil),          // 14: ai-workflow-automation.user.GetUserToolsResponse
	(*RegisterUserToolResponse)(nil),      // 15: ai-workflow-automation.user.RegisterUserToolResponse
	(*GetUserActivityResponse)(nil),       // 16: ai-workflow-automation.user.GetUserActivityResponse
	(*UserProfile)(nil),                   // 17: ai-workflow-automation.user.UserProfile
	(*UserPreferences)(nil),               // 18: ai-workflow-automation.user.UserPreferences
	(*UIPreferences)(nil),                 // 19: ai-workflow-automation.user.UIPreferences
	(*WorkflowPreferences)(nil),           // 20: ai-workflow-automation.user.WorkflowPreferences
	(*NotificationPreferences)(nil),       // 21: ai-workflow-automation.user.NotificationPreferences
	(*SecurityPreferences)(nil),           // 22: ai-workflow-automation.user.SecurityPreferences
	(*UserTool)(nil),                      // 23: ai-workflow-automation.user.UserTool
	(*UserActivity)(nil),                  // 24: ai-workflow-automation.user.UserActivity
	(*UserMetrics)(nil),                   // 25: ai-workflow-automation.user.UserMetrics
	(*ToolUsage)(nil),                     // 26: ai-workflow-automation.user.ToolUsage
	(*LanguagePreference)(nil),            // 27: ai-workflow-automation.user.LanguagePreference
	(*structpb.Struct)(nil),               // 28: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	18, // 0: ai-workflow-automation.user.UpdateUserPreferencesRequest.preferences:type_name -> ai-workflow-automation.user.UserPreferences
	28, // 1: ai-workflow-automation.user.UpdateUserContextRequest.context_updates:type_name -> google.protobuf.Struct
	1,  // 2: ai-workflow-automation.user.GetUserToolsRequest.category:type_name -> ai-workflow-automation.user.ToolCategory
	23, // 3: ai-workflow-automation.user.RegisterUserToolRequest.tool:type_name -> ai-workflow-automation.user.UserTool
	29, // 4: ai-workflow-automation.user.GetUserActivityRequest.start_time:type_name -> google.protobuf.Timestamp
	29, // 5: ai-workflow-automation.user.GetUserActivityRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 6: ai-workflow-automation.user.GetUserActivityRequest.activity_type:type_name -> ai-workflow-automation.user.ActivityType
	17, // 7: ai-workflow-automation.user.GetUserProfileResponse.profile:type_name -> ai-workflow-automation.user.UserProfile
	18, // 8: ai-workflow-automation.user.GetUserProfileResponse.preferences:type_name -> ai-workflow-automation.user.UserPreferences
	23, // 9: ai-workflow-automation.user.GetUserProfileResponse.tools:type_name -> ai-workflow-automation.user.UserTool
	0,  // 10: ai-workflow-automation.user.GetUserProfileResponse.status:type_name -> ai-workflow-automation.user.UserStatus
	18, // 11: ai-workflow-automation.user.UpdateUserPreferencesResponse.updated_preferences:type_name -> ai-workflow-automation.user.UserPreferences
	28, // 12: ai-workflow-automation.user.GetUserContextResponse.context:type_name -> google.protobuf.Struct
	29, // 13: ai-workflow-automation.user.GetUserContextResponse.last_updated:type_name -> google.protobuf.Timestamp
	28, // 14: ai-workflow-automation.user.UpdateUserContextResponse.updated_context:type_name -> google.protobuf.Struct
	23, // 15: ai-workflow-automation.user.GetUserToolsResponse.tools:type_name -> ai-workflow-automation.user.UserTool
	1,  // 16: ai-workflow-automation.user.GetUserToolsResponse.available_categories:type_name -> ai-workflow-automation.user.ToolCategory
	23, // 17: ai-workflow-automation.user.RegisterUserToolResponse.registered_tool:type_name -> ai-workflow-automation.user.UserTool
	24, // 18: ai-workflow-automation.user.GetUserActivityResponse.activities:type_name -> ai-workflow-automation.user.UserActivity
	25, // 19: ai-workflow-automation.user.GetUserActivityResponse.metrics:type_name -> ai-workflow-automation.user.UserMetrics
	29, // 20: ai-workflow-automation.user.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	29, // 21: ai-workflow-automation.user.UserProfile.last_active:type_name -> google.protobuf.Timestamp
	0,  // 22: ai-workflow-automation.user.UserProfile.status:type_name -> ai-workflow-automation.user.UserStatus
	28, // 23: ai-workflow-automation.user.UserProfile.metadata:type_name -> google.protobuf.Struct
	27, // 24: ai-workflow-automation.user.UserPreferences.language:type_name -> ai-workflow-automation.user.LanguagePreference
	19, // 25: ai-workflow-automation.user.UserPreferences.ui_preferences:type_name -> ai-workflow-automation.user.UIPreferences
	20, // 26: ai-workflow-automation.user.UserPreferences.workflow_preferences:type_name -> ai-workflow-automation.user.WorkflowPreferences
	21, // 27: ai-workflow-automation.user.UserPreferences.notification_preferences:type_name -> ai-workflow-automation.user.NotificationPreferences
	22, // 28: ai-workflow-automation.user.UserPreferences.security_preferences:type_name -> ai-workflow-automation.user.SecurityPreferences
	28, // 29: ai-workflow-automation.user.UserPreferences.custom_preferences:type_name -> google.protobuf.Struct
	1,  // 30: ai-workflow-automation.user.UserTool.category:type_name -> ai-workflow-automation.user.ToolCategory
	28, // 31: ai-workflow-automation.user.UserTool.configuration:type_name -> google.protobuf.Struct
	29, // 32: ai-workflow-automation.user.UserTool.registered_at:type_name -> google.protobuf.Timestamp
	29, // 33: ai-workflow-automation.user.UserTool.last_used:type_name -> google.protobuf.Timestamp
	2,  // 34: ai-workflow-automation.user.UserActivity.activity_type:type_name -> ai-workflow-automation.user.ActivityType
	28, // 35: ai-workflow-automation.user.UserActivity.details:type_name -> google.protobuf.Struct
	29, // 36: ai-workflow-automation.user.UserActivity.timestamp:type_name -> google.protobuf.Timestamp
	29, // 37: ai-workflow-automation.user.UserMetrics.first_activity:type_name -> google.protobuf.Timestamp
	29, // 38: ai-workflow-automation.user.UserMetrics.last_activity:type_name -> google.protobuf.Timestamp
	26, // 39: ai-workflow-automation.user.UserMetrics.tool_usage:type_name -> ai-workflow-automation.user.ToolUsage
	29, // 40: ai-workflow-automation.user.ToolUsage.last_used:type_name -> google.protobuf.Timestamp
	3,  // 41: ai-workflow-automation.user.UserService.GetUserProfile:input_type -> ai-workflow-automation.user.GetUserProfileRequest
	4,  // 42: ai-workflow-automation.user.UserService.UpdateUserPreferences:input_type -> ai-workflow-automation.user.UpdateUserPreferencesRequest
	5,  // 43: ai-workflow-automation.user.UserService.GetUserContext:input_type -> ai-workflow-automation.user.GetUserContextRequest
	6,  // 44: ai-workflow-automation.user.UserService.UpdateUserContext:input_type -> ai-workflow-automation.user.UpdateUserContextRequest
	7,  // 45: ai-workflow-automation.user.UserService.GetUserTools:input_type -> ai-workflow-automation.user.GetUserToolsRequest
	8,  // 46: ai-workflow-automation.user.UserService.RegisterUserTool:input_type -> ai-workflow-automation.user.RegisterUserToolRequest
	9,  // 47: ai-workflow-automation.user.UserService.GetUserActivity:input_type -> ai-workflow-automation.user.GetUserActivityRequest
	10, // 48: ai-workflow-automation.user.UserService.GetUserProfile:output_type -> ai-workflow-automation.user.GetUserProfileResponse
	11, // 49: ai-workflow-automation.user.UserService.UpdateUserPreferences:output_type -> ai-workflow-automation.user.UpdateUserPreferencesResponse
	12, // 50: ai-workflow-automation.user.UserService.GetUserContext:output_type -> ai-workflow-automation.user.GetUserContextResponse
	13, // 51: ai-workflow-automation.user.UserService.UpdateUserContext:output_type -> ai-workflow-automation.user.UpdateUserContextResponse
	14, // 52: ai-workflow-automation.user.UserService.GetUserTools:output_type -> ai-workflow-automation.user.GetUserToolsResponse
	15, // 53: ai-workflow-automation.user.UserService.RegisterUserTool:output_type -> ai-workflow-automation.user.RegisterUserToolResponse
	16, // 54: ai-workflow-automation.user.UserService.GetUserActivity:output_type -> ai-workflow-automation.user.GetUserActivityResponse
	48, // [48:55] is the sub-list for method output_type
	41, // [41:48] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		EnumInfos:         file_user_proto_enumTypes,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
