// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: workflow.proto

package protos

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generation stages for streaming workflow creation
type GenerationStage int32

const (
	GenerationStage_STAGE_UNSPECIFIED         GenerationStage = 0
	GenerationStage_STAGE_PARSING_INTENT      GenerationStage = 1
	GenerationStage_STAGE_DISCOVERING_TOOLS   GenerationStage = 2
	GenerationStage_STAGE_GENERATING_STEPS    GenerationStage = 3
	GenerationStage_STAGE_OPTIMIZING_WORKFLOW GenerationStage = 4
	GenerationStage_STAGE_VALIDATING          GenerationStage = 5
	GenerationStage_STAGE_COMPLETE            GenerationStage = 6
	GenerationStage_STAGE_ERROR               GenerationStage = 7
)

// Enum value maps for GenerationStage.
var (
	GenerationStage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_PARSING_INTENT",
		2: "STAGE_DISCOVERING_TOOLS",
		3: "STAGE_GENERATING_STEPS",
		4: "STAGE_OPTIMIZING_WORKFLOW",
		5: "STAGE_VALIDATING",
		6: "STAGE_COMPLETE",
		7: "STAGE_ERROR",
	}
	GenerationStage_value = map[string]int32{
		"STAGE_UNSPECIFIED":         0,
		"STAGE_PARSING_INTENT":      1,
		"STAGE_DISCOVERING_TOOLS":   2,
		"STAGE_GENERATING_STEPS":    3,
		"STAGE_OPTIMIZING_WORKFLOW": 4,
		"STAGE_VALIDATING":          5,
		"STAGE_COMPLETE":            6,
		"STAGE_ERROR":               7,
	}
)

func (x GenerationStage) Enum() *GenerationStage {
	p := new(GenerationStage)
	*p = x
	return p
}

func (x GenerationStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationStage) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_proto_enumTypes[0].Descriptor()
}

func (GenerationStage) Type() protoreflect.EnumType {
	return &file_workflow_proto_enumTypes[0]
}

func (x GenerationStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationStage.Descriptor instead.
func (GenerationStage) EnumDescriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

// Streaming progress message for workflow generation
type WorkflowGenerationProgress struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Stage                    GenerationStage        `protobuf:"varint,1,opt,name=stage,proto3,enum=ai-workflow-automation.workflow.v1.GenerationStage" json:"stage,omitempty"`
	ProgressPercentage       float32                `protobuf:"fixed32,2,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	Message                  string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Details                  string                 `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	EstimatedTimeRemainingMs int64                  `protobuf:"varint,5,opt,name=estimated_time_remaining_ms,json=estimatedTimeRemainingMs,proto3" json:"estimated_time_remaining_ms,omitempty"`
	PartialWorkflow          *WorkflowDefinition    `protobuf:"bytes,6,opt,name=partial_workflow,json=partialWorkflow,proto3" json:"partial_workflow,omitempty"`
	IsComplete               bool                   `protobuf:"varint,7,opt,name=is_complete,json=isComplete,proto3" json:"is_complete,omitempty"`
	ErrorMessage             string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *WorkflowGenerationProgress) Reset() {
	*x = WorkflowGenerationProgress{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowGenerationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowGenerationProgress) ProtoMessage() {}

func (x *WorkflowGenerationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowGenerationProgress.ProtoReflect.Descriptor instead.
func (*WorkflowGenerationProgress) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowGenerationProgress) GetStage() GenerationStage {
	if x != nil {
		return x.Stage
	}
	return GenerationStage_STAGE_UNSPECIFIED
}

func (x *WorkflowGenerationProgress) GetProgressPercentage() float32 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *WorkflowGenerationProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowGenerationProgress) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *WorkflowGenerationProgress) GetEstimatedTimeRemainingMs() int64 {
	if x != nil {
		return x.EstimatedTimeRemainingMs
	}
	return 0
}

func (x *WorkflowGenerationProgress) GetPartialWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.PartialWorkflow
	}
	return nil
}

func (x *WorkflowGenerationProgress) GetIsComplete() bool {
	if x != nil {
		return x.IsComplete
	}
	return false
}

func (x *WorkflowGenerationProgress) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Request Messages
type GenerateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRequest   string                 `protobuf:"bytes,2,opt,name=user_request,json=userRequest,proto3" json:"user_request,omitempty"`
	Context       *structpb.Struct       `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	TestMode      bool                   `protobuf:"varint,5,opt,name=test_mode,json=testMode,proto3" json:"test_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWorkflowRequest) Reset() {
	*x = GenerateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWorkflowRequest) ProtoMessage() {}

func (x *GenerateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GenerateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateWorkflowRequest) GetUserRequest() string {
	if x != nil {
		return x.UserRequest
	}
	return ""
}

func (x *GenerateWorkflowRequest) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GenerateWorkflowRequest) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GetWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // Optional filter by status
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ListWorkflowsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWorkflowsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWorkflowsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkflowsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListWorkflowsRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type UpdateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,3,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Updates       *structpb.Struct       `protobuf:"bytes,4,opt,name=updates,proto3" json:"updates,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkflowRequest) Reset() {
	*x = UpdateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowRequest) ProtoMessage() {}

func (x *UpdateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateWorkflowRequest) GetUpdates() *structpb.Struct {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *UpdateWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type DeleteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowRequest) Reset() {
	*x = DeleteWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowRequest) ProtoMessage() {}

func (x *DeleteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *DeleteWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ValidateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *WorkflowDefinition    `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowRequest) Reset() {
	*x = ValidateWorkflowRequest{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowRequest) ProtoMessage() {}

func (x *ValidateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateWorkflowRequest) GetWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *ValidateWorkflowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Response Messages
type GenerateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Definition    *WorkflowDefinition    `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,6,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Metadata      *GenerationMetadata    `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWorkflowResponse) Reset() {
	*x = GenerateWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWorkflowResponse) ProtoMessage() {}

func (x *GenerateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GenerateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *GenerateWorkflowResponse) GetDefinition() *WorkflowDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *GenerateWorkflowResponse) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *GenerateWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateWorkflowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GenerateWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *GenerateWorkflowResponse) GetMetadata() *GenerationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *WorkflowDefinition    `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowResponse) GetWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *GetWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetWorkflowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*WorkflowDefinition  `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*WorkflowDefinition {
	if x != nil {
		return x.Workflows
	}
	return nil
}

func (x *ListWorkflowsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListWorkflowsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWorkflowsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ListWorkflowsResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type UpdateWorkflowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UpdatedWorkflow *WorkflowDefinition    `protobuf:"bytes,2,opt,name=updated_workflow,json=updatedWorkflow,proto3" json:"updated_workflow,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId   string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateWorkflowResponse) Reset() {
	*x = UpdateWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkflowResponse) ProtoMessage() {}

func (x *UpdateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*UpdateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateWorkflowResponse) GetUpdatedWorkflow() *WorkflowDefinition {
	if x != nil {
		return x.UpdatedWorkflow
	}
	return nil
}

func (x *UpdateWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateWorkflowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpdateWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type DeleteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CorrelationId string                 `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkflowResponse) Reset() {
	*x = DeleteWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkflowResponse) ProtoMessage() {}

func (x *DeleteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeleteWorkflowResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeleteWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type ValidateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Errors        []*ValidationError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	Warnings      []string               `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CorrelationId string                 `protobuf:"bytes,5,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateWorkflowResponse) Reset() {
	*x = ValidateWorkflowResponse{}
	mi := &file_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateWorkflowResponse) ProtoMessage() {}

func (x *ValidateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*ValidateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *ValidateWorkflowResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *ValidateWorkflowResponse) GetErrors() []*ValidationError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ValidateWorkflowResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateWorkflowResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ValidateWorkflowResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

// Data Models
type WorkflowDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Steps         []*WorkflowStep        `protobuf:"bytes,5,rep,name=steps,proto3" json:"steps,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowDefinition) Reset() {
	*x = WorkflowDefinition{}
	mi := &file_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDefinition) ProtoMessage() {}

func (x *WorkflowDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDefinition.ProtoReflect.Descriptor instead.
func (*WorkflowDefinition) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *WorkflowDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowDefinition) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WorkflowDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkflowDefinition) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *WorkflowDefinition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowDefinition) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WorkflowDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowDefinition) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type WorkflowStep struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ToolName         string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Parameters       *structpb.Struct       `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Dependencies     []string               `protobuf:"bytes,5,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	ParallelEligible bool                   `protobuf:"varint,6,opt,name=parallel_eligible,json=parallelEligible,proto3" json:"parallel_eligible,omitempty"`
	RetryCount       int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	RetryDelay       int32                  `protobuf:"varint,9,opt,name=retry_delay,json=retryDelay,proto3" json:"retry_delay,omitempty"`
	Metadata         *structpb.Struct       `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *WorkflowStep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStep) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *WorkflowStep) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *WorkflowStep) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *WorkflowStep) GetParallelEligible() bool {
	if x != nil {
		return x.ParallelEligible
	}
	return false
}

func (x *WorkflowStep) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *WorkflowStep) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *WorkflowStep) GetRetryDelay() int32 {
	if x != nil {
		return x.RetryDelay
	}
	return 0
}

func (x *WorkflowStep) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GenerationMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalSteps            int32                  `protobuf:"varint,1,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	ToolCount             int32                  `protobuf:"varint,2,opt,name=tool_count,json=toolCount,proto3" json:"tool_count,omitempty"`
	GenerationTimeSeconds float32                `protobuf:"fixed32,3,opt,name=generation_time_seconds,json=generationTimeSeconds,proto3" json:"generation_time_seconds,omitempty"`
	UsedEntities          []string               `protobuf:"bytes,4,rep,name=used_entities,json=usedEntities,proto3" json:"used_entities,omitempty"`
	ParsedIntent          *structpb.Struct       `protobuf:"bytes,5,opt,name=parsed_intent,json=parsedIntent,proto3" json:"parsed_intent,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GenerationMetadata) Reset() {
	*x = GenerationMetadata{}
	mi := &file_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationMetadata) ProtoMessage() {}

func (x *GenerationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationMetadata.ProtoReflect.Descriptor instead.
func (*GenerationMetadata) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *GenerationMetadata) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *GenerationMetadata) GetToolCount() int32 {
	if x != nil {
		return x.ToolCount
	}
	return 0
}

func (x *GenerationMetadata) GetGenerationTimeSeconds() float32 {
	if x != nil {
		return x.GenerationTimeSeconds
	}
	return 0
}

func (x *GenerationMetadata) GetUsedEntities() []string {
	if x != nil {
		return x.UsedEntities
	}
	return nil
}

func (x *GenerationMetadata) GetParsedIntent() *structpb.Struct {
	if x != nil {
		return x.ParsedIntent
	}
	return nil
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ValidationError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidationError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\x14verbilio.workflow.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x98\x03\n" +
	"\x1aWorkflowGenerationProgress\x12;\n" +
	"\x05stage\x18\x01 \x01(\x0e2%.ai-workflow-automation.workflow.v1.GenerationStageR\x05stage\x12/\n" +
	"\x13progress_percentage\x18\x02 \x01(\x02R\x12progressPercentage\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x04 \x01(\tR\adetails\x12=\n" +
	"\x1bestimated_time_remaining_ms\x18\x05 \x01(\x03R\x18estimatedTimeRemainingMs\x12S\n" +
	"\x10partial_workflow\x18\x06 \x01(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\x0fpartialWorkflow\x12\x1f\n" +
	"\vis_complete\x18\a \x01(\bR\n" +
	"isComplete\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\xcc\x01\n" +
	"\x17GenerateWorkflowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fuser_request\x18\x02 \x01(\tR\vuserRequest\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12\x1b\n" +
	"\ttest_mode\x18\x05 \x01(\bR\btestMode\"u\n" +
	"\x12GetWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\x9c\x01\n" +
	"\x14ListWorkflowsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xca\x01\n" +
	"\x15UpdateWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x03 \x01(\tR\tnewStatus\x121\n" +
	"\aupdates\x18\x04 \x01(\v2\x17.google.protobuf.StructR\aupdates\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"x\n" +
	"\x15DeleteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\x9f\x01\n" +
	"\x17ValidateWorkflowRequest\x12D\n" +
	"\bworkflow\x18\x01 \x01(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\bworkflow\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\xe9\x02\n" +
	"\x18GenerateWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12H\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\n" +
	"definition\x128\n" +
	"\x05steps\x18\x03 \x03(\v2\".ai-workflow-automation.workflow.v1.WorkflowStepR\x05steps\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x06 \x01(\tR\rcorrelationId\x12D\n" +
	"\bmetadata\x18\a \x01(\v2(.ai-workflow-automation.workflow.v1.GenerationMetadataR\bmetadata\"\xbf\x01\n" +
	"\x13GetWorkflowResponse\x12D\n" +
	"\bworkflow\x18\x01 \x01(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\bworkflow\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xe4\x01\n" +
	"\x15ListWorkflowsResponse\x12F\n" +
	"\tworkflows\x18\x01 \x03(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\tworkflows\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xeb\x01\n" +
	"\x16UpdateWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12S\n" +
	"\x10updated_workflow\x18\x02 \x01(\v2(.ai-workflow-automation.workflow.v1.WorkflowDefinitionR\x0fupdatedWorkflow\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\x96\x01\n" +
	"\x16DeleteWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\"\xcf\x01\n" +
	"\x18ValidateWorkflowResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12=\n" +
	"\x06errors\x18\x02 \x03(\v2%.ai-workflow-automation.workflow.v1.ValidationErrorR\x06errors\x12\x1a\n" +
	"\bwarnings\x18\x03 \x03(\tR\bwarnings\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12%\n" +
	"\x0ecorrelation_id\x18\x05 \x01(\tR\rcorrelationId\"\xf0\x02\n" +
	"\x12WorkflowDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x128\n" +
	"\x05steps\x18\x05 \x03(\v2\".ai-workflow-automation.workflow.v1.WorkflowStepR\x05steps\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x123\n" +
	"\bmetadata\x18\a \x01(\v2\x17.google.protobuf.StructR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf1\x02\n" +
	"\fWorkflowStep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x127\n" +
	"\n" +
	"parameters\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12\"\n" +
	"\fdependencies\x18\x05 \x03(\tR\fdependencies\x12+\n" +
	"\x11parallel_eligible\x18\x06 \x01(\bR\x10parallelEligible\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12\x1f\n" +
	"\vretry_delay\x18\t \x01(\x05R\n" +
	"retryDelay\x123\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\bmetadata\"\xef\x01\n" +
	"\x12GenerationMetadata\x12\x1f\n" +
	"\vtotal_steps\x18\x01 \x01(\x05R\n" +
	"totalSteps\x12\x1d\n" +
	"\n" +
	"tool_count\x18\x02 \x01(\x05R\ttoolCount\x126\n" +
	"\x17generation_time_seconds\x18\x03 \x01(\x02R\x15generationTimeSeconds\x12#\n" +
	"\rused_entities\x18\x04 \x03(\tR\fusedEntities\x12<\n" +
	"\rparsed_intent\x18\x05 \x01(\v2\x17.google.protobuf.StructR\fparsedIntent\"\x93\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x121\n" +
	"\adetails\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adetails*\xd5\x01\n" +
	"\x0fGenerationStage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STAGE_PARSING_INTENT\x10\x01\x12\x1b\n" +
	"\x17STAGE_DISCOVERING_TOOLS\x10\x02\x12\x1a\n" +
	"\x16STAGE_GENERATING_STEPS\x10\x03\x12\x1d\n" +
	"\x19STAGE_OPTIMIZING_WORKFLOW\x10\x04\x12\x14\n" +
	"\x10STAGE_VALIDATING\x10\x05\x12\x12\n" +
	"\x0eSTAGE_COMPLETE\x10\x06\x12\x0f\n" +
	"\vSTAGE_ERROR\x10\a2\x9c\x06\n" +
	"\x0fWorkflowService\x12q\n" +
	"\x10GenerateWorkflow\x12-.ai-workflow-automation.workflow.v1.GenerateWorkflowRequest\x1a..ai-workflow-automation.workflow.v1.GenerateWorkflowResponse\x12{\n" +
	"\x16GenerateWorkflowStream\x12-.ai-workflow-automation.workflow.v1.GenerateWorkflowRequest\x1a0.ai-workflow-automation.workflow.v1.WorkflowGenerationProgress0\x01\x12b\n" +
	"\vGetWorkflow\x12(.ai-workflow-automation.workflow.v1.GetWorkflowRequest\x1a).ai-workflow-automation.workflow.v1.GetWorkflowResponse\x12h\n" +
	"\rListWorkflows\x12*.ai-workflow-automation.workflow.v1.ListWorkflowsRequest\x1a+.ai-workflow-automation.workflow.v1.ListWorkflowsResponse\x12k\n" +
	"\x0eUpdateWorkflow\x12+.ai-workflow-automation.workflow.v1.UpdateWorkflowRequest\x1a,.ai-workflow-automation.workflow.v1.UpdateWorkflowResponse\x12k\n" +
	"\x0eDeleteWorkflow\x12+.ai-workflow-automation.workflow.v1.DeleteWorkflowRequest\x1a,.ai-workflow-automation.workflow.v1.DeleteWorkflowResponse\x12q\n" +
	"\x10ValidateWorkflow\x12-.ai-workflow-automation.workflow.v1.ValidateWorkflowRequest\x1a..ai-workflow-automation.workflow.v1.ValidateWorkflowResponseB8Z6github.com/ai-workflow-automation/api-gateway/pkg/grpc_client/protosb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_workflow_proto_goTypes = []any{
	(GenerationStage)(0),               // 0: ai-workflow-automation.workflow.v1.GenerationStage
	(*WorkflowGenerationProgress)(nil), // 1: ai-workflow-automation.workflow.v1.WorkflowGenerationProgress
	(*GenerateWorkflowRequest)(nil),    // 2: ai-workflow-automation.workflow.v1.GenerateWorkflowRequest
	(*GetWorkflowRequest)(nil),         // 3: ai-workflow-automation.workflow.v1.GetWorkflowRequest
	(*ListWorkflowsRequest)(nil),       // 4: ai-workflow-automation.workflow.v1.ListWorkflowsRequest
	(*UpdateWorkflowRequest)(nil),      // 5: ai-workflow-automation.workflow.v1.UpdateWorkflowRequest
	(*DeleteWorkflowRequest)(nil),      // 6: ai-workflow-automation.workflow.v1.DeleteWorkflowRequest
	(*ValidateWorkflowRequest)(nil),    // 7: ai-workflow-automation.workflow.v1.ValidateWorkflowRequest
	(*GenerateWorkflowResponse)(nil),   // 8: ai-workflow-automation.workflow.v1.GenerateWorkflowResponse
	(*GetWorkflowResponse)(nil),        // 9: ai-workflow-automation.workflow.v1.GetWorkflowResponse
	(*ListWorkflowsResponse)(nil),      // 10: ai-workflow-automation.workflow.v1.ListWorkflowsResponse
	(*UpdateWorkflowResponse)(nil),     // 11: ai-workflow-automation.workflow.v1.UpdateWorkflowResponse
	(*DeleteWorkflowResponse)(nil),     // 12: ai-workflow-automation.workflow.v1.DeleteWorkflowResponse
	(*ValidateWorkflowResponse)(nil),   // 13: ai-workflow-automation.workflow.v1.ValidateWorkflowResponse
	(*WorkflowDefinition)(nil),         // 14: ai-workflow-automation.workflow.v1.WorkflowDefinition
	(*WorkflowStep)(nil),               // 15: ai-workflow-automation.workflow.v1.WorkflowStep
	(*GenerationMetadata)(nil),         // 16: ai-workflow-automation.workflow.v1.GenerationMetadata
	(*ValidationError)(nil),            // 17: ai-workflow-automation.workflow.v1.ValidationError
	(*structpb.Struct)(nil),            // 18: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 19: google.protobuf.Timestamp
}
var file_workflow_proto_depIdxs = []int32{
	0,  // 0: ai-workflow-automation.workflow.v1.WorkflowGenerationProgress.stage:type_name -> ai-workflow-automation.workflow.v1.GenerationStage
	14, // 1: ai-workflow-automation.workflow.v1.WorkflowGenerationProgress.partial_workflow:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	18, // 2: ai-workflow-automation.workflow.v1.GenerateWorkflowRequest.context:type_name -> google.protobuf.Struct
	18, // 3: ai-workflow-automation.workflow.v1.UpdateWorkflowRequest.updates:type_name -> google.protobuf.Struct
	14, // 4: ai-workflow-automation.workflow.v1.ValidateWorkflowRequest.workflow:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	14, // 5: ai-workflow-automation.workflow.v1.GenerateWorkflowResponse.definition:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	15, // 6: ai-workflow-automation.workflow.v1.GenerateWorkflowResponse.steps:type_name -> ai-workflow-automation.workflow.v1.WorkflowStep
	16, // 7: ai-workflow-automation.workflow.v1.GenerateWorkflowResponse.metadata:type_name -> ai-workflow-automation.workflow.v1.GenerationMetadata
	14, // 8: ai-workflow-automation.workflow.v1.GetWorkflowResponse.workflow:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	14, // 9: ai-workflow-automation.workflow.v1.ListWorkflowsResponse.workflows:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	14, // 10: ai-workflow-automation.workflow.v1.UpdateWorkflowResponse.updated_workflow:type_name -> ai-workflow-automation.workflow.v1.WorkflowDefinition
	17, // 11: ai-workflow-automation.workflow.v1.ValidateWorkflowResponse.errors:type_name -> ai-workflow-automation.workflow.v1.ValidationError
	15, // 12: ai-workflow-automation.workflow.v1.WorkflowDefinition.steps:type_name -> ai-workflow-automation.workflow.v1.WorkflowStep
	18, // 13: ai-workflow-automation.workflow.v1.WorkflowDefinition.metadata:type_name -> google.protobuf.Struct
	19, // 14: ai-workflow-automation.workflow.v1.WorkflowDefinition.created_at:type_name -> google.protobuf.Timestamp
	19, // 15: ai-workflow-automation.workflow.v1.WorkflowDefinition.updated_at:type_name -> google.protobuf.Timestamp
	18, // 16: ai-workflow-automation.workflow.v1.WorkflowStep.parameters:type_name -> google.protobuf.Struct
	18, // 17: ai-workflow-automation.workflow.v1.WorkflowStep.metadata:type_name -> google.protobuf.Struct
	18, // 18: ai-workflow-automation.workflow.v1.GenerationMetadata.parsed_intent:type_name -> google.protobuf.Struct
	18, // 19: ai-workflow-automation.workflow.v1.ValidationError.details:type_name -> google.protobuf.Struct
	2,  // 20: ai-workflow-automation.workflow.v1.WorkflowService.GenerateWorkflow:input_type -> ai-workflow-automation.workflow.v1.GenerateWorkflowRequest
	2,  // 21: ai-workflow-automation.workflow.v1.WorkflowService.GenerateWorkflowStream:input_type -> ai-workflow-automation.workflow.v1.GenerateWorkflowRequest
	3,  // 22: ai-workflow-automation.workflow.v1.WorkflowService.GetWorkflow:input_type -> ai-workflow-automation.workflow.v1.GetWorkflowRequest
	4,  // 23: ai-workflow-automation.workflow.v1.WorkflowService.ListWorkflows:input_type -> ai-workflow-automation.workflow.v1.ListWorkflowsRequest
	5,  // 24: ai-workflow-automation.workflow.v1.WorkflowService.UpdateWorkflow:input_type -> ai-workflow-automation.workflow.v1.UpdateWorkflowRequest
	6,  // 25: ai-workflow-automation.workflow.v1.WorkflowService.DeleteWorkflow:input_type -> ai-workflow-automation.workflow.v1.DeleteWorkflowRequest
	7,  // 26: ai-workflow-automation.workflow.v1.WorkflowService.ValidateWorkflow:input_type -> ai-workflow-automation.workflow.v1.ValidateWorkflowRequest
	8,  // 27: ai-workflow-automation.workflow.v1.WorkflowService.GenerateWorkflow:output_type -> ai-workflow-automation.workflow.v1.GenerateWorkflowResponse
	1,  // 28: ai-workflow-automation.workflow.v1.WorkflowService.GenerateWorkflowStream:output_type -> ai-workflow-automation.workflow.v1.WorkflowGenerationProgress
	9,  // 29: ai-workflow-automation.workflow.v1.WorkflowService.GetWorkflow:output_type -> ai-workflow-automation.workflow.v1.GetWorkflowResponse
	10, // 30: ai-workflow-automation.workflow.v1.WorkflowService.ListWorkflows:output_type -> ai-workflow-automation.workflow.v1.ListWorkflowsResponse
	11, // 31: ai-workflow-automation.workflow.v1.WorkflowService.UpdateWorkflow:output_type -> ai-workflow-automation.workflow.v1.UpdateWorkflowResponse
	12, // 32: ai-workflow-automation.workflow.v1.WorkflowService.DeleteWorkflow:output_type -> ai-workflow-automation.workflow.v1.DeleteWorkflowResponse
	13, // 33: ai-workflow-automation.workflow.v1.WorkflowService.ValidateWorkflow:output_type -> ai-workflow-automation.workflow.v1.ValidateWorkflowResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		EnumInfos:         file_workflow_proto_enumTypes,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
