# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Chat Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartChatSession = channel.unary_unary(
                '/ai-workflow-automation.chat.ChatService/StartChatSession',
                request_serializer=chat__pb2.StartChatSessionRequest.SerializeToString,
                response_deserializer=chat__pb2.StartChatSessionResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_stream(
                '/ai-workflow-automation.chat.ChatService/SendMessage',
                request_serializer=chat__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatMessageResponse.FromString,
                _registered_method=True)
        self.GetChatHistory = channel.unary_unary(
                '/ai-workflow-automation.chat.ChatService/GetChatHistory',
                request_serializer=chat__pb2.GetChatHistoryRequest.SerializeToString,
                response_deserializer=chat__pb2.GetChatHistoryResponse.FromString,
                _registered_method=True)
        self.EndChatSession = channel.unary_unary(
                '/ai-workflow-automation.chat.ChatService/EndChatSession',
                request_serializer=chat__pb2.EndChatSessionRequest.SerializeToString,
                response_deserializer=chat__pb2.EndChatSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionContext = channel.unary_unary(
                '/ai-workflow-automation.chat.ChatService/GetSessionContext',
                request_serializer=chat__pb2.GetSessionContextRequest.SerializeToString,
                response_deserializer=chat__pb2.GetSessionContextResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Chat Service
    """

    def StartChatSession(self, request, context):
        """Start a new chat session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Send a message and get streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatHistory(self, request, context):
        """Get chat history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndChatSession(self, request, context):
        """End chat session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionContext(self, request, context):
        """Get session context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartChatSession,
                    request_deserializer=chat__pb2.StartChatSessionRequest.FromString,
                    response_serializer=chat__pb2.StartChatSessionResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=chat__pb2.SendMessageRequest.FromString,
                    response_serializer=chat__pb2.ChatMessageResponse.SerializeToString,
            ),
            'GetChatHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChatHistory,
                    request_deserializer=chat__pb2.GetChatHistoryRequest.FromString,
                    response_serializer=chat__pb2.GetChatHistoryResponse.SerializeToString,
            ),
            'EndChatSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndChatSession,
                    request_deserializer=chat__pb2.EndChatSessionRequest.FromString,
                    response_serializer=chat__pb2.EndChatSessionResponse.SerializeToString,
            ),
            'GetSessionContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionContext,
                    request_deserializer=chat__pb2.GetSessionContextRequest.FromString,
                    response_serializer=chat__pb2.GetSessionContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai-workflow-automation.chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai-workflow-automation.chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat Service
    """

    @staticmethod
    def StartChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.chat.ChatService/StartChatSession',
            chat__pb2.StartChatSessionRequest.SerializeToString,
            chat__pb2.StartChatSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai-workflow-automation.chat.ChatService/SendMessage',
            chat__pb2.SendMessageRequest.SerializeToString,
            chat__pb2.ChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.chat.ChatService/GetChatHistory',
            chat__pb2.GetChatHistoryRequest.SerializeToString,
            chat__pb2.GetChatHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndChatSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.chat.ChatService/EndChatSession',
            chat__pb2.EndChatSessionRequest.SerializeToString,
            chat__pb2.EndChatSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.chat.ChatService/GetSessionContext',
            chat__pb2.GetSessionContextRequest.SerializeToString,
            chat__pb2.GetSessionContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
