# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import user_pb2 as user__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """User Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserProfile = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/GetUserProfile',
                request_serializer=user__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserProfileResponse.FromString,
                _registered_method=True)
        self.UpdateUserPreferences = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/UpdateUserPreferences',
                request_serializer=user__pb2.UpdateUserPreferencesRequest.SerializeToString,
                response_deserializer=user__pb2.UpdateUserPreferencesResponse.FromString,
                _registered_method=True)
        self.GetUserContext = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/GetUserContext',
                request_serializer=user__pb2.GetUserContextRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserContextResponse.FromString,
                _registered_method=True)
        self.UpdateUserContext = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/UpdateUserContext',
                request_serializer=user__pb2.UpdateUserContextRequest.SerializeToString,
                response_deserializer=user__pb2.UpdateUserContextResponse.FromString,
                _registered_method=True)
        self.GetUserTools = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/GetUserTools',
                request_serializer=user__pb2.GetUserToolsRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserToolsResponse.FromString,
                _registered_method=True)
        self.RegisterUserTool = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/RegisterUserTool',
                request_serializer=user__pb2.RegisterUserToolRequest.SerializeToString,
                response_deserializer=user__pb2.RegisterUserToolResponse.FromString,
                _registered_method=True)
        self.GetUserActivity = channel.unary_unary(
                '/ai-workflow-automation.user.UserService/GetUserActivity',
                request_serializer=user__pb2.GetUserActivityRequest.SerializeToString,
                response_deserializer=user__pb2.GetUserActivityResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """User Service
    """

    def GetUserProfile(self, request, context):
        """Get user profile and preferences
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPreferences(self, request, context):
        """Update user preferences
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserContext(self, request, context):
        """Get user context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserContext(self, request, context):
        """Update user context
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserTools(self, request, context):
        """Get user tools and capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterUserTool(self, request, context):
        """Register new user tool
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserActivity(self, request, context):
        """Get user activity and metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=user__pb2.GetUserProfileRequest.FromString,
                    response_serializer=user__pb2.GetUserProfileResponse.SerializeToString,
            ),
            'UpdateUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPreferences,
                    request_deserializer=user__pb2.UpdateUserPreferencesRequest.FromString,
                    response_serializer=user__pb2.UpdateUserPreferencesResponse.SerializeToString,
            ),
            'GetUserContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserContext,
                    request_deserializer=user__pb2.GetUserContextRequest.FromString,
                    response_serializer=user__pb2.GetUserContextResponse.SerializeToString,
            ),
            'UpdateUserContext': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserContext,
                    request_deserializer=user__pb2.UpdateUserContextRequest.FromString,
                    response_serializer=user__pb2.UpdateUserContextResponse.SerializeToString,
            ),
            'GetUserTools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserTools,
                    request_deserializer=user__pb2.GetUserToolsRequest.FromString,
                    response_serializer=user__pb2.GetUserToolsResponse.SerializeToString,
            ),
            'RegisterUserTool': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUserTool,
                    request_deserializer=user__pb2.RegisterUserToolRequest.FromString,
                    response_serializer=user__pb2.RegisterUserToolResponse.SerializeToString,
            ),
            'GetUserActivity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserActivity,
                    request_deserializer=user__pb2.GetUserActivityRequest.FromString,
                    response_serializer=user__pb2.GetUserActivityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai-workflow-automation.user.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai-workflow-automation.user.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """User Service
    """

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/GetUserProfile',
            user__pb2.GetUserProfileRequest.SerializeToString,
            user__pb2.GetUserProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/UpdateUserPreferences',
            user__pb2.UpdateUserPreferencesRequest.SerializeToString,
            user__pb2.UpdateUserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/GetUserContext',
            user__pb2.GetUserContextRequest.SerializeToString,
            user__pb2.GetUserContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/UpdateUserContext',
            user__pb2.UpdateUserContextRequest.SerializeToString,
            user__pb2.UpdateUserContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/GetUserTools',
            user__pb2.GetUserToolsRequest.SerializeToString,
            user__pb2.GetUserToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterUserTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/RegisterUserTool',
            user__pb2.RegisterUserToolRequest.SerializeToString,
            user__pb2.RegisterUserToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserActivity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai-workflow-automation.user.UserService/GetUserActivity',
            user__pb2.GetUserActivityRequest.SerializeToString,
            user__pb2.GetUserActivityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
